### ISSUE TITLE
Missing support for special characters in torrent client URL

### ISSUE THREAD

**Issue by keldian** [mmgoodnow/cross-seed#100]
My rutorrent password contains a ! character and as a result I cannot connect cross-seed to rTorrent.

Inputting the password as is `rtorrentRpcUrl: "http://user:password!@rutorrent/RPC2",` 
Returns invalid URL error:
```
info: Validating your configuration...
(node:7) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_URL]: Invalid URL: http://user:password!@rutorrent/RPC2
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at new RTorrent (/usr/src/app/dist/src/clients/RTorrent.js:52:68)
    at instantiateDownloadClient (/usr/src/app/dist/src/clients/TorrentClient.js:14:24)
    at Object.getClient (/usr/src/app/dist/src/clients/TorrentClient.js:22:9)
    at Object.doStartupValidation (/usr/src/app/dist/src/startup.js:9:44)
    at Command.<anonymous> (/usr/src/app/dist/src/cmd.js:109:29)
    at Command.listener [as _actionHandler] (/usr/src/app/node_modules/commander/index.js:907:31)
    at Command._parseCommand (/usr/src/app/node_modules/commander/index.js:1491:14)
    at Command._dispatchSubcommand (/usr/src/app/node_modules/commander/index.js:1436:18)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Escaping the character by using URL encoding (! = %21) / `rtorrentRpcUrl: "http://user:password%21@rutorrent/RPC2",`
Causes auth failure:
```
Info: Validating your configuration...
Error: Failed to reach rTorrent at http://user:password%21@rutorrent/RPC2
```
BTW, it would be cool if the log were more explicit as to the cause of the error being auth failure. I spent like an hour fiddling with the host block of the URL until I figured out the issue isn't there.

Anyway, special characters are essential for security when a web UI is exposed to the internet.
Maybe consider Base64 encoding? And perhaps break apart the setting like most apps do. Something like:
```
rtorrentHost: "http://host",
rtorrentRpcUrl: "RPC2",
rtorrentPort: "80",
rtorrentCreds: "dXNlcjpwYXNz", // Base64 encoded user:pass
```

Thanks.

**Comment by mmgoodnow** [comment]
This is an interesting bug…

My password contains lots of special characters and it works just fine. 

I don't think it's the trailing exclamation point. You can see in the stack trace that it's failing at `new URL` which is part of the standard library for Node. When I tried creating your URL in the node REPL, it worked just fine:
```
> new URL("http://user:password!@rutorrent/RPC2")
URL {
  href: 'http://user:password!@rutorrent/RPC2',
  origin: 'http://rutorrent',
  protocol: 'http:',
  username: 'user',
  password: 'password!',
  host: 'rutorrent',
  hostname: 'rutorrent',
  port: '',
  pathname: '/RPC2',
  search: '',
  searchParams: URLSearchParams {},
  hash: '' }
```

Does your username/password contain any of the following characters?

`/`, `\`, `"`, `@`, `:`

**Comment by mmgoodnow** [comment]
To debug this, my suggestion is to go into the node REPL and try doing `new URL("xyz")` with the original url first, to confirm that it is indeed the URL constructor, and that my code isn't somehow mangling the URL along the way (unlikely but anything's possible). Then, I would recommend removing one suspicious character at a time from the user/pass until it starts working.

**Comment by keldian** [comment]
Sorry, I was tired when I made this post after hours of troubleshooting, and got things mixed up somehow. It's actually a trailing `?` that causes the Node error–there's no other special character in the password, and none in the username. Originally I had `@` in the password and that didn't work with cross-seed, so then I changed it to a string without special characters at all and that did work–hence my deduction that special characters are not supported. Then I figured it was time for a new password anyway which is how I ended up with the `?` one, but there was never a `!`.

As for the Node output (not sure if this what you meant):
```
$ docker exec -ti cross-seed node
Welcome to Node.js v12.22.1.
Type ".help" for more information.
> new URL("http://****:*******?@rutorrent/RPC2")
Uncaught TypeError [ERR_INVALID_URL]: Invalid URL: http://****:*******?@rutorrent/RPC2
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at REPL1:1:1
    at Script.runInThisContext (vm.js:120:18)
    at REPLServer.defaultEval (repl.js:442:29)
    at bound (domain.js:427:14)
    at REPLServer.runBound [as eval] (domain.js:440:12)
    at REPLServer.onLine (repl.js:777:10)
    at REPLServer.emit (events.js:326:22)
    at REPLServer.EventEmitter.emit (domain.js:483:12) {
  input: 'http://****:*******?@rutorrent/RPC2',
  code: 'ERR_INVALID_URL'
}
>
```

**Comment by mmgoodnow** [comment]
Support for percent-encoded URL components added in v2.5.2
