### ISSUE TITLE
[rtorrent] injecting torrents for incomplete downloads

### ISSUE THREAD

**Issue by pummra** [mmgoodnow/cross-seed#101]
I have cross-seed working on a schedule using crontab and has been working well. There are however moments when cross-seed runs whilst a torrent is downloading. In these instances cross-seed is still looking for matches rather than only checking when complete. 

I have been running cross-seed on verbose to see if I can see why it would be doing this, but nothing obvious in the output. The below is the configdump. 

```
[[verbose[[: [configdump] {
  jackettServerUrl: 'xxxx',
  jackettApiKey: 'xxxx',
  trackers: [],
  torrentDir: '/path/to/.session',
  outputDir: '/path/to/watch_folder',
  searchAll: false,
  verbose: true,
  action: 'inject',
  rtorrentRpcUrl: 'xxx,
  offset: 0,
  delay: 10,
  includeEpisodes: true,
  excludeOlder: 60
}
```

The log is mostly full of prefilters so won't share it all here. Any ideas why it might be doing this?

**Comment by ajhorvath20** [comment]
Hi this one is fixed few weeks ago 

`today at 18:18:53 warn: Found A.B.2.2021.2160p.WEB-DL.DDP5.1.Atmos.HDR.HEVC-CMRG.mkv on ABC - skipping incomplete torrent`

**Comment by pummra** [comment]
I'm running version 2.4.0 which is the latest version.

**Comment by mmgoodnow** [comment]
Are you doing direct injection? Skipping incomplete torrents is only supported with direct injection.

**Comment by pummra** [comment]
Yep, direct injection.

**Comment by mmgoodnow** [comment]
Hmm, I may not have implemented the unfinished download checking for rtorrent.
