### ISSUE TITLE
FR: Add Prowlarr Support

### ISSUE THREAD

**Issue by bakerboy448** [mmgoodnow/cross-seed#104]
Title

Add Prowlarr Support

would likely need to use the /search and /indexer endpoints; no /all exists nor is it planned for an aggregate endpoint to exist

I see https://github.com/mmgoodnow/cross-seed/issues/83 was closed

so to address some of those comments

>it would be a significant amount of work - currently I'm using the private Jackett JSON api, not Torznab. If I were ever to support both I would use Torznab.

Indeed.  Anything on the prowlarr side that can be done to make this easier?

> In order for Jackett competitors to succeed they need to continuously support hundreds of trackers. Seeing as Prowlarr is very young, I'd like to see it mature into a stable version that supports many trackers and keeps up with maintenance first.
Feel free to reopen or comment again when you think that Prowlarr has proven that its in it for the long haul.

> continuously support hundreds of trackers

Yup, we do.

> stable version

Betas are rolling along and working in PROD without issue by a few thousand.  and the initial alpha group has been using it in Prod since Feb/March

> keeps up with maintenance first.

on top of it

> Prowlarr has proven that its in it for the long haul.

It's the Servarr team that brought you Readarr/Lidarr/Radarr (and the Servarr Wiki), so yes.

**Comment by mmgoodnow** [comment]
Fair enough, and I appreciate you coming over here to offer help as well. Would you mind closing this out and posting it as a comment on #83?
