### ISSUE TITLE
Normal Behavior?

### ISSUE THREAD

**Issue by UnPossible-Me** [mmgoodnow/cross-seed#106]
Hello,
So I'm just starting out, can't say I completely understand everything, but... we learn as we go right?
Anyways, I've setup the config file as given in the wiki (For deluge) and [Issue 58](https://github.com/mmgoodnow/cross-seed/issues/58).

When I run `cross-seed search` I get:
```
Validating your configuration...
Your configuration is valid!
Found 55 torrents, 9 suitable to search for matches
.
.
.
Done! Found 0 cross seeds from 9 original torrents
```

That is ahhh... less than ideal.
So is there something I'm doing incorrectly? Shouldn't it scan more torrents and at least find a few? How should I proceed?

**Comment by Torkiliuz** [comment]
You could try changing searchAll to "true", as it will search for more torrents for a possible match. Not all torrents have a matching torrent across trackers; some are archived, some are unpacked, have different names, etc..

**Comment by mmgoodnow** [comment]
This is most likely normal behavior, especially if you're not searching very many trackers.

**Comment by UnPossible-Me** [comment]
Hmm, I'll take these into consideration, I using roughly 15 trackers right now (given the type of torrent), and it seems to only scan torrents that are movies.

**Comment by UnPossible-Me** [comment]
Changing `searchAll` to `"true"` seems to have fixed it, scanned all of them now. 
I got a couple of hits, and `Unsupported: magnet link detected` which from the issues I understand isn't yet supported correct?

**Comment by mmgoodnow** [comment]
Magnet links will never be supported because they don't contain enough information to verify a match
