### ISSUE TITLE
[FEATURE] - Redact secrets from the logs

### ISSUE THREAD

**Issue by afraazali** [mmgoodnow/cross-seed#130]
Going through my logs I noticed that the jackett API key is shown in the logs. Would it be possible to implement the following logic into Winston to redact the API key:

https://github.com/winstonjs/winston/issues/1079#issuecomment-825115754

This would/could also be updated to redact other patterns from the log in the future if need be.

**Comment by mmgoodnow** [comment]
[v2.8.0](https://github.com/mmgoodnow/cross-seed/releases/tag/v2.8.0)
