### ISSUE TITLE
Tixati

### ISSUE THREAD

**Issue by uptightgnome** [mmgoodnow/cross-seed#131]

**Comment by mmgoodnow** [comment]
For this to get implemented, please provide documentation for Tixati's API.

**Comment by uptightgnome** [comment]
There's no official API but there's this, not sure if it would suffice
https://github.com/MisanthropicShayna/tixati-python-api-cli

**Comment by mmgoodnow** [comment]
Unfortunately, without a documented, official, stable API I won't be able to implement this, especially since Tixati is not widely used.
