### ISSUE TITLE
rtorrent giving error when connecting to cross-seed

### ISSUE THREAD

**Issue by ajhorvath20** [mmgoodnow/cross-seed#134]
Hi, I am getting this error when I try to connect to `rtorrent`

```
$ docker logs cross-seed 
(node:1) UnhandledPromiseRejectionWarning: /config/config.js:42
        rtorrentRpcUrl: http://192.168.1.167:3000/RPC2,
```
This is my rtorrent.rc https://pastebin.com/MJqnSvum

And this is my cross-seed config https://pastebin.com/WZx13CcJ

Thank you

**Comment by ajhorvath20** [comment]
I added the `quotes` around the url and now I am getting this 
```
info: Validating your configuration...
error: Failed to reach rTorrent at http://192.168.1.167:3000/RPC2
info: Validating your configuration...
error: Failed to reach rTorrent at http://192.168.1.167:3000/RPC2
```

**Comment by ajhorvath20** [comment]
@mmgoodnow thats awesome you know what I'm doing wrong here because I'm using flood too and getting these messages?

Yoi are using flood so it will be great if you can guide me what I need to put in my URL. 

Thanks

**Comment by ajhorvath20** [comment]
I evenly tried with this this URL and still didnt work

`rtorrentRpcUrl: "http://username:password@192.168.1.247:3000/RPC2"`

**Comment by ajhorvath20** [comment]
I got this info from flood maintainer but I think you did it straight away with your flood setup :)

![Screenshot_20210904-174132_Discord](https://user-images.githubusercontent.com/65309559/132102028-11edaa34-fc47-4a92-ae2e-bb322831ae42.jpg)

**Comment by mmgoodnow** [comment]
I'll see what I can do.
