### ISSUE TITLE
Feature Request: Torrent name filter to avoid scene groups

### ISSUE THREAD

**Issue by key-str0ke** [mmgoodnow/cross-seed#140]
Would love a feature to filter out scene groups / words in Torrent titles.  Would really help stop unnecessary torrent searches for groups that usually are on a single tracker or are modified when uploaded to other private trackers which just wastes remote resources.

**Comment by mmgoodnow** [comment]
might be possible to achieve this with grep - see more in https://github.com/mmgoodnow/cross-seed/discussions/208

**Comment by mmgoodnow** [comment]
bundled into #210
