### ISSUE TITLE
Notification sends with empty tracker lost

### ISSUE THREAD

**Issue by afraazali** [mmgoodnow/cross-seed#142]
I’m not sure if the notification is sending incorrect data or send the notification even when there aren’t matches.

I seem to get the messages, every 30 minutes (I run cross seed on cron). Below is an example 

cross-seed
Found movie.mkv on

The notification code is supposed to send the list of trackers it was found on, but the list is always blank.

I’ll continue to test.

**Comment by mmgoodnow** [comment]
fixed in v2.9.1
