### ISSUE TITLE
latest version doesn't seem to be working on OSX.

### ISSUE THREAD

**Issue by str0ke-milw0rm** [mmgoodnow/cross-seed#143]
Recently upgraded to v2.9.1 and I haven't had a cross seed since.  Searched for torrents in the last 600 minutes, 0 cross-seeds found, reverted to 2.8.0 and 6 were found.

ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G8022

npm --version
6.14.15

npx cross-seed search -u http://jackett:9117 -k key -i /torrents/ -s /watch/ -a -x 120 -r 29

**Comment by mmgoodnow** [comment]
It's possible this is related to some changes with the exclude-older flag. I'll look into it!

**Comment by str0ke-milw0rm** [comment]
Thank you so much!  Appreciate your time.

**Comment by mmgoodnow** [comment]
this should be fixed in v2.9.2. It was specfically a regression regarding the use of `trackers: []` in your config file, so if you weren't using that then you should reopen.
