### ISSUE TITLE
FR - Enable Automatic Torrent Management

### ISSUE THREAD

**Issue by Drazzilb08** [mmgoodnow/cross-seed#144]
Is it possible to have cross-seed add torrents with Automatic Torrent Management.

Usecase: Hypothetically there could be a torrent that is tagged BTN was downloaded first and put into the incomplete-tv category. It does not get imported in sonarr yet because the show is still showing up as TBA. Meanwhile cross-seed runs and finds a torrent and adds it to qbit at the incomplete-tv category. Sonarr finally imports the torrent and the original torrent gets moved to a new category completed-tv and the save path gets changed. The cross-seed torrent does not change to the new path when changing the category to the completed-tv

Reason:  So if the cross-seeded torrent doesn't have auto torrent mgmt enabled and I manually change the category to completed-tv after the original moved. I would have to not only change the category but also the save path as well because if auto torrent mgmt is disabled then the category could be changed to completed-tv while the save path could be pointing to the incomplete directory

Alt Solution: Omit categories #95

**Comment by bobokun** [comment]
Also would love the additional to this feature even if it's an option to be configured in the config

**Comment by bakerboy448** [comment]
It looks like this is a simple single line commit to change false to true  maybe?

**Comment by mmgoodnow** [comment]
ATM makes the file-matching a lot more complicated. I'll need someone more familiar with the qbit api and qbit's behavior in general to make it work fully

**Comment by bakerboy448** [comment]
How so out of curiosity?

**Comment by mmgoodnow** [comment]
I don't really remember but I butted heads with it a lot when I was initially implementing qbit support.

**Comment by bobokun** [comment]
This request has been implemented in https://github.com/StuffAnThings/qbit_manage/issues/66

**Comment by mmgoodnow** [comment]
v3.3.3
