### ISSUE TITLE
[Request] Rotate log files

### ISSUE THREAD

**Issue by KnifeFed** [mmgoodnow/cross-seed#146]
My `verbose.log` is currently 215 MB and contains 92000+ lines. It would be nice if logs could be rotated at a fixed size, say 50 MB, and the previous one renamed to `verbose.log.bak1` etc. (basically like how qBittorrent does it).

**Comment by KnifeFed** [comment]
Thanks for implementing this! Will older logs be pruned after some time?

**Comment by mmgoodnow** [comment]
2 weeks

**Comment by KnifeFed** [comment]
Perfect!

**Comment by mmgoodnow** [comment]
Of course, LMK if it doesn't end up working.
