### ISSUE TITLE
Search keeps failing 

### ISSUE THREAD

**Issue by Fiala06** [mmgoodnow/cross-seed#150]
Any ideas why I would be getting this? Config is valid but did update the program and recreate the config yet still have the same issue. 

`info: [6/1904] Searching for Pokemon.Detective.Pikachu.2019.2160p.UHD.Blu-ray.Remux.HEVC.HDR10.TrueHD.Atmos.7.1-SURFINBIRD
(node:842794) UnhandledPromiseRejectionWarning: TypeError: Intl.ListFormat is not a constructor
    at findOnOtherSites (/usr/local/lib/node_modules/cross-seed/dist/src/pipeline.js:42:18)
(node:842794) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:842794) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

fiala06@s61415:~$ ^C`

**Comment by mmgoodnow** [comment]
I think that means your node version is out of date

**Comment by Fiala06** [comment]
Thanks seems like that was it!  Updated to v14.18.1 and so far its working.
