### ISSUE TITLE
Docker Daemon not finding results

### ISSUE THREAD

**Issue by DuzAwe** [mmgoodnow/cross-seed#158]
Hey, 

Getting alot of info: [server] Found 0 torrents. For example 
`info: [server] Found 0 torrents for { name: 'Tick.Tick.BOOM!.2021.1080p.NF.WEB-DL.DDP5.1.Atmos.x264-EVO' }`

When I manually look, there are exact matches on the second page in Jackett

`configVersion: 1,
    jackettServerUrl: "******************",
    jackettApiKey: "********************",
    delay: 15,
    excludeRecentSearch: 1440,
    excludeOlder: 10080,
    trackers: ["bb", "animebytes", "anthelion", "beyond-hd", "blutopia", "digitalcore", "filelist", "iptorrents", "nebulance", "theempire", "torrentday", "torrentdb", "torrentleech", "torrentseeds", "peerjunkies"],
    torrentDir: "/home/rslsync/Resilio\ Sync/sync",
    outputDir: "/home/rslsync/Resilio\ Sync/crossseed",
    includeEpisodes: false,
    searchAll: true,
    action: "inject",
    qbittorrentUrl: "http://username:password@localhost:8080",

**Comment by Wmartin417** [comment]
Have the same issue.

**Comment by mmgoodnow** [comment]
do you have verbose logging enabled? there might be hints there as to why search results are getting rejected

**Comment by DuzAwe** [comment]
Lots of different file tree messages

**Comment by mmgoodnow** [comment]
what happens if you run cross-seed diff on those two torrents?

**Comment by DuzAwe** [comment]
Sorry how do I run cross-seed diff? Cant see any syntax in the wiki.

**Comment by mmgoodnow** [comment]
It's in the command line help menu `cross-seed -h`

**Comment by DuzAwe** [comment]
I think this can be close the main file seems to be a different size, I ran a test just now with something a bit more popular and found all the same matches with daemon that I did manually with Jackett
