### ISSUE TITLE
Add Systemd File

### ISSUE THREAD

**Issue by bakerboy448** [mmgoodnow/cross-seed#159]
below is a systemd for the daemon that should work for the wiki

/etc/systemd/system/xseed.service
```none
[Unit]
Description=Cross Seed Search Daemon
After=network.target qbittorrent jackett
Wants=network-online.target qbittorrent jackett
[Service]
User={user}
Group={group}
Restart=always
Type=simple
ExecStart=cross-seed daemon
[Install]
WantedBy=multi-user.target
```

**Comment by bakerboy448** [comment]
also for qbit

```bash
curl -XPOST http://localhost:2468/api/webhook --data-urlencode 'name="%N"' --data-urlencode 'infoHash="%I"'--data-urlencode 'trackers=torrentleech' --data-urlencode 'trackers=myanonamouse' --data-urlencode 'trackers=torrentdb' --data-urlencode 'trackers=broadcasthenet' --data-urlencode 'trackers=beyond-hd-api' --data-urlencode 'outputDir=/data/media/_downloads/torrents.xseed'
```

**Comment by mmgoodnow** [comment]
Thanks! I'll put this in the wiki. It looks like it's crashing due to the single quotes wrapping each query param; maybe try wrapping in bash -c?

**Comment by bakerboy448** [comment]
`bash -c "curl -XPOST http://localhost:2468/api/webhook --data-urlencode 'name=Mad.Max.1979.BluRay.1080p.DD.5.1.x264-BHDStudio.mp4' --data-urlencode 'infoHash=56a9289f5da956d694aa7497a452c25a3e753274' --data-urlencode 'trackers=torrentleech' --data-urlencode 'trackers=myanonamouse' --data-urlencode 'trackers=torrentdb' --data-urlencode 'trackers=broadcasthenet' --data-urlencode 'trackers=beyond-hd-api' --data-urlencode 'outputDir=/data/media/_downloads/torrents.xseed'"` did it

will update qbit accordingly

e.g.
```
bash -c "curl -XPOST http://localhost:2468/api/webhook --data-urlencode 'name="%N"' --data-urlencode 'infoHash="%I"'--data-urlencode 'trackers=torrentleech' --data-urlencode 'trackers=myanonamouse' --data-urlencode 'trackers=torrentdb' --data-urlencode 'trackers=broadcasthenet' --data-urlencode 'trackers=beyond-hd-api' --data-urlencode 'outputDir=/data/media/_downloads/torrents.xseed'"
```

**Comment by bakerboy448** [comment]
For Qbit

need to create a bash file e.g. `xseed-qbitdaemon.sh` and ensure it is executable
```
#!/bin/bash
Name=$1
Hash=$2

curl -XPOST http://localhost:2468/api/webhook \
--data-urlencode name="$Name" \
--data-urlencode infoHash="$Hash" \
--data-urlencode trackers=torrentleech \
--data-urlencode trackers=myanonamouse \
--data-urlencode trackers=torrentdb \
--data-urlencode trackers=broadcasthenet \
--data-urlencode trackers=beyond-hd-api \
--data-urlencode outputDir=/data/media/_downloads/torrents.xseed
```

then have qbit call it as

`/full/path/to/script/xseed-qbitdaemon.sh "%N" "%I"`

have not yet tested the qbit call, but have otherwise tested the script

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/wiki/Systemd
