### ISSUE TITLE
Unraid Template 

### ISSUE THREAD

**Issue by ajhorvath20** [mmgoodnow/cross-seed#162]
Hi, is it possible to create unraid template. I don't think it's been requested before. 

Thank you

**Comment by mmgoodnow** [comment]
Contributions welcome.

**Comment by DuzAwe** [comment]
How to integrate it with the Unraid CA system https://forums.unraid.net/topic/57181-docker-faq/#comment-566084 as the author it would be likely best for you to control this part.

Below is a template that should work. 

```
<?xml version="1.0"?>
<Container version="2">
  <Name>cross-seed</Name>
  <Repository>mmgoodnow/cross-seed</Repository>
  <Registry>https://hub.docker.com/r/mmgoodnow/cross-seed/</Registry>
  <Network>bridge</Network>
  <Privileged>false</Privileged>
  <Support>https://github.com/mmgoodnow/cross-seed/</Support>
  <Project>https://github.com/mmgoodnow/cross-seed/</Project>
  <Overview>Fully-automatic cross-seeding with Jackett&#xD;https://hub.docker.com/r/mmgoodnow/cross-seed/</Overview>
   <Category>Tools<Category/>
   <WebUI>http://[IP]:[PORT:2468]</WebUI>
  <Icon>/plugins/dynamix.docker.manager/images/question.png</Icon>
  <PostArgs>daemon</PostArgs>
  <Config Name="config" Target="/config" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">/mnt/user/appdata/cross-seed/</Config>
  <Config Name="input" Target="/torrents" Default="" Mode="ro" Description="" Type="Path" Display="always" Required="false" Mask="false">torrent file location</Config>
  <Config Name="output" Target="/output" Default="" Mode="rw" Description="" Type="Path" Display="always" Required="false" Mask="false">location of monitored folder</Config>
  <Config Name="port" Target="2468" Default="" Mode="tcp" Description="" Type="Port" Display="always" Required="false" Mask="false">2468</Config>
</Container>
```

**Comment by mmgoodnow** [comment]
no idea how unraid works, is it not possible for end-users to install cross-seed themselves? It looks like I have to jump through a lot of hoops to do something I don't really understand here. If end users can install cross-seed themselves, I'd vastly prefer that. Otherwise I think I'll just not support unraid at all.

**Comment by DuzAwe** [comment]
@mmgoodnow They can simply use the docker and map the variables as needed. The Docker install guide is all you really need. If I get time today I can write something up. 

@ajhorvath20 This request may be better suited by reaching out to selfhosters, Hotio or linuxserver. You could also make a request on the unriad form.

**Comment by mmgoodnow** [comment]
Ah thanks for the info @DuzAwe! Feel free to post any blurbs in the comments of this issue; I'll be online to pull them into the wiki

**Comment by DuzAwe** [comment]
@mmgoodnow NP, Thanks for the work you've done.

**A basic install guide for Unraid.**
To install in Unraid the easiest set up will be to use the Community Applications App found [here](https://forums.unraid.net/topic/38582-plug-in-community-applications/). Once the app is installed go to the app tab and search cross-seed, hit enter and you should get no results then hit the Click Here To Get More Results From DockerHub link. 

That should populate the search page with the existing docker hub images. For the sake of support use the mmgoodnow/cross-seed image. Hit install and once downloaded you should be presented with the familiar unraid docker page.

Hit the advanced options switch in the top right. 

In the Post Arguments: section add daemon.  

Set privileged to on 

Click Add another Path, Port, Variable, Label or Device and add Config Type: Path, Name: Config, Container Path: /config, Host Path:/mnt/user/appdata/cross-seed/, Access Mode: Read / Write

Click Add another Path, Port, Variable, Label or Device and add Config Type: Path, Name: input, Container Path: /torrents, Host Path:/mnt/user/appdata/"PATH TO YOUR TORRENT FILES", Access Mode: Read Only

Click Add another Path, Port, Variable, Label or Device and add Config Type: Path,  Name: output, Container Path: /output, Host Path:/mnt/user/appdata/"PATH TO YOUR TORRENT CLIENTS MONITORED FOLDER"

Click Add another Path, Port, Variable, Label or Device and add Config Type: Port,  Name: port, Container Port: 2468, Host Port: 2468, Connection Type: TCP

Attached screenshot of what it should now look like. That should be that. You will still need to create a config by starting the docker and editing it further as per the wiki.

![screenshot-cross-seed](https://user-images.githubusercontent.com/2813049/147599328-6032688e-45e4-43cf-87f6-a070829e1a1b.png)

**Comment by mmgoodnow** [comment]
Added to wiki, thanks so much @DuzAwe!

**Comment by LilTrublMakr** [comment]
Just a heads up, it is not creating a config file automatically on start up.

I am getting `error: required option '-u, --jackett-server-url <url>' not specified` when trying to start the container. I can't console in to generate a config file like stated [here](https://github.com/mmgoodnow/cross-seed/wiki/Configuration-file) because the container will not stay started. The link to the example config file is broken but I was able to find the one for docker [here](https://github.com/mmgoodnow/cross-seed/blob/master/src/config.template.docker.cjs). It does not seem to be in a format that I am familiar with. Do I keep it as the cjs format or do I need to transfer it to a json file?

**Comment by mmgoodnow** [comment]
If you map your config dir to a real path you should be able to modify the config file without having to enter the container.

**Comment by mmgoodnow** [comment]
It should be called config.js
