### ISSUE TITLE
Built-in cron

### ISSUE THREAD

**Issue by bobokun** [mmgoodnow/cross-seed#164]
Is it possible to trigger search while in daemon mode?

**Comment by afraazali** [comment]
I have a simple script that does this from the *arrs. It pings the daemon with a commit hash and that starts off a search

**Comment by bobokun** [comment]
That sounds amazing if you could share the script and your workflow with *arrs. I was hesitant with using daemon because of how I have it set up with *arrs it would add the cross seed torrent to the incomplete category before the import happened. I was thinking of adding a delay to the a script but if the *arrs had issue importing then it would still add it to the incomplete category.

**Comment by afraazali** [comment]
So I have a bash script that gets executed through the “Connect > Custom script”. I have it running on import and upgrade. Below is the script:

```
curl -XPOST ${CROSS_SEED_HOST}/api/webhook \
  -H 'Content-Type: application/json' \
  --data '{"infoHash":"'"${sonarr_download_id}"'"}'

exit 0
```

The radarr one is identical, but the variable is `radarr_download_id`.

The `CROSS_SEED_HOST` is just an env var I have set in my container that’s just the the url (or in my case container service) to the cross seed daemon.

**Comment by bobokun** [comment]
Thank you for sharing!

**Comment by bobokun** [comment]
Is there a way to trigger a normal search in daemon through the script? Not to search for a specific torrent hash but all your torrents. The reason why I want to use search on top of daemon is for the use case when a new torrent gets uploaded on one tracker and gets added but the other trackers don't have the torrent up yet so daemon won't add any cross seed because they don't exist on the other trackers . Search will then go through and pick up any missing cross seeds that get added at a later time. Daemon only works well when it's not a brand new torrent.

**Comment by afraazali** [comment]
For that use case I just run the search, non daemon, in a container that runs it via cron.

**Comment by mmgoodnow** [comment]
I have some nebulous plans about adding a cron type function into the daemon mode but you're on your own until then

**Comment by bobokun** [comment]
> For that use case I just run the search, non daemon, in a container that runs it via cron.

Okay in that case I'll need two cross seed containers , one that is constantly running in daemon mode and the other that will be scheduled with Cron to run search

**Comment by bobokun** [comment]
> I have some nebulous plans about adding a cron type function into the daemon mode but you're on your own until then

Do you see any potential issues that can happen with caching if two containers are pointing to the same source and running simultaneously? If daemon run is running and a search gets triggered with Cron could that have a negative effect on cache?

**Comment by mmgoodnow** [comment]
Maybe but the cache is just an optimization so it should not cause problems

**Comment by afraazali** [comment]
I haven’t had an issues with it. The daemon container just sits there waiting for one of the *arrs to make a request to search. I have the other container running cron, that runs the search every 3 hours.

**Comment by bobokun** [comment]
btw @afraazali I realized there's no need to have two docker containers running. You can achieve both with just one container. Just have the container running as daemon mode and to trigger search create a script that runs on cron that will execute the search using `docker exec cross-seed cross-seed search`

**Comment by afraazali** [comment]
Excellent!

**Comment by Drazzilb08** [comment]
> So I have a bash script that gets executed through the “Connect > Custom script”. I have it running on import and upgrade. Below is the script:
> 
> ```
> curl -XPOST ${CROSS_SEED_HOST}/api/webhook \
>   -H 'Content-Type: application/json' \
>   --data '{"infoHash":"'"${sonarr_download_id}"'"}'
> 
> exit 0
> ```
> 
> The radarr one is identical, but the variable is `radarr_download_id`.
> 
> The `CROSS_SEED_HOST` is just an env var I have set in my container that’s just the the url (or in my case container service) to the cross seed daemon.

So found a bit of an issue with this, It seems that Sonarr pings the script on EVERY SINGLE IMPORT of a season pack, so depending on how big the season is it is pinging xseed/jackett/tracker that many times for the same information (which can seem kind of fishy). 
Now, this isn't a problem for single episodes and movies as those are single files and single import calls to the script. However, season packs call multiple times.

Thoughts on this issue?

**Comment by BaukeZwart** [comment]
Sorry to tap into this thread, does anybody know why I'm getting this error in the Sonarr log when using CS in daemon mode?
```2022-01-19 23:45:11.8|Error|sonarr-cross-seed.sh|  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-01-19 23:45:11.8|Error|sonarr-cross-seed.sh|                                 Dload  Upload   Total   Spent    Left  Speed
2022-01-19 23:45:11.9|Error|sonarr-cross-seed.sh|  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
2022-01-19 23:45:11.9|Error|sonarr-cross-seed.sh|100    49    0     0  100    49      0    438 --:--:-- --:--:-- --:--:--   441```
this is the script I'm running in Sonarr.
```#!/bin/bash
CLIENT='qBittorrent'
if [ "$sonarr_download_client" == "$CLIENT" ]
then
  curl -XPOST http://cross-seed:2468/api/webhook \
  --data-urlencode infoHash=${sonarr_download_id}
fi

exit 0```

**Comment by afraazali** [comment]
> So found a bit of an issue with this, It seems that Sonarr pings the script on EVERY SINGLE IMPORT of a season pack, so depending on how big the season is it is pinging xseed/jackett/tracker that many times for the same information (which can seem kind of fishy). Now, this isn't a problem for single episodes and movies as those are single files and single import calls to the script. However, season packs call multiple times.
> 
> Furthermore, when it pings the season pack on the first episode it will then add the cross-seed torrent to the incorrect save path (incomplete) because the save path isn't changed yet (not all episodes have been imported). Then sonarr comes along and moves the original to the `completed` category.
> 
> Thoughts on this issue or possibly something via API?

Sorry @Drazzilb08 just seeing this now. I haven't downloaded any season packs, only single episodes. Looking through the wiki docs on Sonarr, I don't see a variable that could signify that it's a season pack. I'll need to reach out to the Sonarr team to see if there's something I'm missing.

**Comment by afraazali** [comment]
> Sorry to tap into this thread, does anybody know why I'm getting this error in the Sonarr log when using CS in daemon mode?

Have you tried running the script directly from the command line to see what the output of the script is?

**Comment by mmgoodnow** [comment]
@Drazzilb08 I would recommend hitting the web hook from your download client's "on download finished" functionality rather than Sonarr if at all possible.

**Comment by dvonte93** [comment]
> @Drazzilb08 I would recommend hitting the web hook from your download client's "on download finished" functionality rather than Sonarr if at all possible.

How would you go about doing this? I use qbit if that helps.

**Comment by keldian** [comment]
@dvonte93 It says how here: https://github.com/mmgoodnow/cross-seed/wiki/Daemon-Mode
