### ISSUE TITLE
Could not reach Jackett at http://localhost:9117/jackett

### ISSUE THREAD

**Issue by wyvernx23** [mmgoodnow/cross-seed#165]
I made a fresh cross-seed config.js file on "machine #2". I have also copied and pasted a confirmed working cross-seed config.js file from a previous machine ("machine #1") For the machine #2 having the error, I keep getting this error when inputting:

cross-seed search
error: Could not reach Jackett at http://127.0.0.1:9117/jackett/api/v2.0/indexers/all/results?apikey=*******

from config.js, here is the data:
    jackettServerUrl: "http://127.0.0.1:9117/jackett",
    jackettApiKey: "(confirmed correct from jackett)"

**Comment by bakerboy448** [comment]
Is Jackett on the exact same machine the script is running on?
127.0.0.1 is localhost which is literally that machine (or container if docker)

**Comment by wyvernx23** [comment]
Hi bakerboy, yes it is running on the same machine as everything else

**Comment by mmgoodnow** [comment]
are you using docker or anything else weird (unraid or something)?

there's not much complicated going on in the "connecting to jackett" part of cross-seed. What happens when you use curl to send a request directly to jackett's api? 

`http://127.0.0.1:9117/jackett/api/v2.0/indexers/all/results?apikey=<your api key>&Query=asdf`

**Comment by wyvernx23** [comment]
Hi @mmgoodnow , I am not using docker and this is one of the only program I have on my mini computer.  i pasted "http://127.0.0.1:9117/jackett/api/v2.0/indexers/all/results?apikey=<myapikeypastedin>&Query=asdf" into microsoft edge (updated to latest version).

Here is the result. 
This 127.0.0.1 page can’t be found
No webpage was found for the web address: http://127.0.0.1:9117/jackett/api/v2.0/indexers/all/results?apikey=<deleted>&Query=asdf
HTTP ERROR 404

**Comment by wyvernx23** [comment]
I just noticed my jackett API key is the same on both computer 1 and 2. Since Jackett on the first computer 1 worked, I presume computer 2 (when I transferred over all the data via C&P) would have a different API key and this copy/paste potentially overwrote something. I do not know how to fix this though.

**Comment by mmgoodnow** [comment]
When you visit the Jackett web ui, what is its url?

**Comment by wyvernx23** [comment]
http://127.0.0.1:9117/UI/Dashboard

**Comment by mmgoodnow** [comment]
Delete the /jackett part
