### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by vaparr** [mmgoodnow/cross-seed#181]
After upgrading to latest, i am now getting this error:

today at 6:00:02 PM SyntaxError: Unexpected end of JSON input
today at 6:00:02 PM    at JSON.parse (<anonymous>)
today at 6:00:02 PM    at JSONFileSync.read (file:///usr/src/app/node_modules/lowdb/lib/adapters/JSONFileSync.js:25:25)
today at 6:00:02 PM    at LowSync.read (file:///usr/src/app/node_modules/lowdb/lib/LowSync.js:24:34)
today at 6:00:02 PM    at file:///usr/src/app/dist/db.js:15:4
today at 6:00:02 PM    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
today at 6:00:02 PM    at async Loader.import (internal/modules/esm/loader.js:178:24)
today at 6:00:02 PM    at async Object.loadESM (internal/process/esm_loader.js:68:5)
today at 6:19:02 PM file:///usr/src/app/node_modules/lowdb/lib/adapters/JSONFileSync.js:25
today at 6:19:02 PM            return JSON.parse(data);

**Comment by mmgoodnow** [comment]
Looks like your cache file may have gotten corrupted. Take a look at it and fix the problem, or just delete it, and that should fix your problem.

**Comment by vaparr** [comment]
Looks like my cache.json file got corrupted, and is now 0 bytes..  This happens everytime i restart cross-seed

**Comment by vaparr** [comment]
Sorry, you can close.. My cache file is 72MB, and if cross-seed gets stopped during a run, it will corrupt it

**Comment by mmgoodnow** [comment]
Thanks for writing in, that's actually very helpful information.
