### ISSUE TITLE
Have cross-seed grab all of the info hashes from the session dir so torrents aren't downloaded multiple times

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#186]
I used cross-seed to cross seed a torrent to another tracker.  I ran the script again with the same input and was expecting a message similar to `You are already seeding this torrent` but instead it downloaded the torrent again.

**Comment by mmgoodnow** [comment]
cross-seed does exactly that. Any torrent files in your inputDir will be rejected as INFO_HASH_ALREADY_EXISTS

**Comment by mmgoodnow** [comment]
Are you sure the torrent in question was sitting in your input dir?

**Comment by newadventure079** [comment]
As the title says, I'm talking about the session dir, not the input dir.

**Comment by newadventure079** [comment]
My bad :)
