### ISSUE TITLE
All cross-seed to search based on Jackett tags, type, or test status

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#187]
You can search in Jackett for private trackers only, for example, and Jackett will append `&filter=type%3Aprivate` to its search string.  

It'd be nice if we could have cross-seed use this functionality and query based on test status (passed, failed), tracker type (private, public, semi-private) and indexers that have tags associated with them

![Screen Shot 2022-01-06 at 8 45 25 PM](https://user-images.githubusercontent.com/84156407/148488168-25c15f5a-11be-4016-950d-11b7886b9676.jpg)

**Comment by mmgoodnow** [comment]
Any functionality specific to Jackett is not going to be worked on as of https://github.com/mmgoodnow/cross-seed/pull/179
