### ISSUE TITLE
Search by season/ep through torznab

### ISSUE THREAD

**Issue by ludviglundgren** [mmgoodnow/cross-seed#191]
Hi. Neat project here.

I recently tried to run it with a Prowlarr torznab indexer to THE big tv tracker. But it could not find anything because it searched with `title S0X` and for some reason they don't support that. Searching manually, with that same torznab url and in Prowlarr without the season in the title do yield results.

I haven't looked at how the release name parsing is done, but if you could make it parse a title without season in it, it would work great for that site, and possibly others too.

**Comment by bakerboy448** [comment]
Searching just the title would not be feasible due to the sheer number of releases for a series.

Which indexer?

**Comment by ludviglundgren** [comment]
This is for BTN. I saw some similar discussions on Reddit where you answered as well, and I do get that but in this case it breaks it sadly.

**Comment by ludviglundgren** [comment]
Their api, tho a bit limited and wonky to work with because jsonrpc, do work with this query. But making this tool conform to that specifically will probably break other indexers.

```
{
	"jsonrpc": "2.0",
	"method": "getTorrentsSearch",
	"params": ["redacted-api-key", {"search": "parks and recreation season 4"}, 100],
	"id": 1
}
```

@bakerboy448 Just checked with a manual search in Prowlarr as well, and that same query do work and return results. It just doesn't like the short for s04 for some reason. :shrug:

**Comment by mmgoodnow** [comment]
Not sure what I can really do here. I'd rather not be in the business of adding tweaks for a single tracker. 

How is it possible that searching on BTN of all places doesn't return results for a query such as `parks and recreation s04?` does it work directly on the website's search functionality?

**Comment by ludviglundgren** [comment]
Totally understand that decision. Yeah, well their api was built back in 2012 and don't think much have changed since :)

No it does not, so they probably use the same controllers/services or whatever for site view and api. So that kinda sucks, and sadly makes this tool almost useless for btn. I had 3 matches out of 120 or something that I ran it wirh.

**Comment by bakerboy448** [comment]
if you know the seasons and episodes if you do - you should just pass those as S/E torznab params

**Comment by mmgoodnow** [comment]
> but may want to check with a caps call to confirm they're supported first

yeah, that's the rub, currently I don't really have infrastructure to keep track of which trackers have which caps. It's something I've considered though - does it work well? I've heard over the years that a lot of sites don't work very well searching that way ("BHD is the first tracker I've found that plays nice with Sonarr", etc)

**Comment by bakerboy448** [comment]
....I don't follow 
torznab standards support a caps call and thus prowlarr or jackett will report what search types the trackers support

it's the exact same logic \*arrs use for determining what to send to the indexer.

**Comment by mmgoodnow** [comment]
ah, so that style of searching is only marked as supported in the caps if the tracker itself exposes that sort of thing?

**Comment by mmgoodnow** [comment]
What does sonarr do if searching by season/episode isn't supported for a given tracker?

**Comment by bakerboy448** [comment]
> ah, so that style of searching is only marked as supported in the caps if the tracker itself exposes that sort of thing?

correct (or rather jackett/prowlarr report it per the tracker's definition)

> What does sonarr do if searching by season/episode isn't supported for a given tracker?

fall back to just plain old query string searches

**Comment by mmgoodnow** [comment]
Does BTN support searching by season/ep?

**Comment by bakerboy448** [comment]
> Does BTN support searching by season/ep?

Yes

https://github.com/Prowlarr/Prowlarr/blob/62f6670a212b282a42beab2aa6ec407473d9bf1e/src/NzbDrone.Core/Indexers/Definitions/BroadcastheNet/BroadcastheNet.cs#L58

**Comment by ludviglundgren** [comment]
How does search with that look like? Looking [here in the code](https://github.com/Prowlarr/Prowlarr/blob/a5e13ca776b629a432a389981235e77f350a915d/src/NzbDrone.Core/Indexers/IndexerCapabilities.cs#L267) then the param `season` should be usable righr? 

 `/api?t=search&q=Showname&season=1` ? That still gives all results with btn :thinking:

**Comment by bakerboy448** [comment]
> How does search with that look like? Looking [here in the code](https://github.com/Prowlarr/Prowlarr/blob/a5e13ca776b629a432a389981235e77f350a915d/src/NzbDrone.Core/Indexers/IndexerCapabilities.cs#L267) then the param `season` should be usable righr? 
> 
> 
> 
>  `/api?t=search&q=Showname&season=1` ? That still gives all results with btn :thinking: 

It's torznab spec

Search is for queries only

You need to do tv search if you want tv supported

Ditto for movie

https://torznab.github.io/spec-1.3-draft/torznab/Specification-v1.3.html#torznab-api-specification

**Comment by ludviglundgren** [comment]
Yeah just figured that out. I hadn't looked at how torznab actually works until yesterday. I wrote my own cross-seed tool instead when this wasn't working as I expected.

**Comment by mmgoodnow** [comment]
Alright, I've got a PR up to add support for this. Please test it out if you can:
- Docker: Please pull from the tag `search-by-season-and-ep`
- CLI: please clone the repo, checkout the `search-by-season-and-ep` branch, run `npm ci`, `npm link`, and then `npm link cross-seed`.

**Comment by mmgoodnow** [comment]
Hey @ludviglundgren can you confirm this is working for BTN?

**Comment by ludviglundgren** [comment]
> Hey @ludviglundgren can you confirm this is working for BTN?

Will try it out later today and get back to you 👍

**Comment by mmgoodnow** [comment]
@ludviglundgren Any updates here?
