### ISSUE TITLE
Replace "_" with spaces when searching

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#195]
I think `.` are already replaced by spaces but we should add `_` to that list too.  This is probably more relevant for DVDs and BluRays.

Below, cross-seed should have searched for `KNIGHTS OF THE CITY` instead of `KNIGHTS_OF_THE_CITY`
```
info: [18/46] Searching for KNIGHTS_OF_THE_CITY
verbose: [torznab] http://192.168.1.110:9696/24/api?apikey=[REDACTED]&t=search&q=KNIGHTS_OF_THE_CITY
```

**Comment by mmgoodnow** [comment]
v3.2.0
