### ISSUE TITLE
Docker user binding not working?

### ISSUE THREAD

**Issue by KnifeFed** [mmgoodnow/cross-seed#198]
I'm running a Docker container on Unraid and I have a `user: 99:100` binding, yet every log file etc. gets created by root. Am I doing something wrong?

**Comment by mmgoodnow** [comment]
hmm thats weird. I also run using docker with a user binding and my logs all get created by the proper user. Maybe try chowning -R the entire config dir to 99:100?

**Comment by KnifeFed** [comment]
It was my fault. I had added it as an environment variable. If anyone else on Unraid is wondering (since it's not available on CA yet), you need to add:
 `--user="99:100"` in `Extra Parameters`.
