### ISSUE TITLE
Search only newer files?

### ISSUE THREAD

**Issue by Fiala06** [mmgoodnow/cross-seed#20]
I could be missing something but is there a way to only search newer torrent files? Right now it's searching about 500 out of 2k torrents. Takes awhile.

Would love a option to search say files created within X amount of days. I've tried the offset option and guess I don't really understand what it does. Each time I run it say -o 490 (with 500 searchable) I get 10 completely different searches.

**Comment by mmgoodnow** [comment]
Interesting that you're getting different searches every time with the offset option, that makes it pretty much useless lol. I'll look into that. 

If the torrents in your torrent folder have timestamps that actually mean something you could use a `find` command to list the files created after a certain date and then copy those into a different folder, although you might get duplicates from that. Autotorrent should be able to throw the duplicates away though I think

**Comment by Fiala06** [comment]
So didn't misinterpret it. :) 

Otherwise it's been working awesome! Haven't figured out my safest route to automate this. Believe I'll need to run a few instances of the script for the different directories that sonarr/radarr ect creates due to labels. Then figure out how autotools will know which directory to use.

**Comment by mmgoodnow** [comment]
I'm interested in your input on automation. I would love if you could lay out your ideal use case. Right now I'm working on automating it into my own setup and my main problem at the moment is the labeling thing.

**Comment by mmgoodnow** [comment]
I am looking into the bug you described about the offset giving you different searches every time but I can't reproduce the behavior. Could you give me a little more information?

Does this happen back-to-back? Like you run -o 490, you see 10 searches, then you run -o 490 again immediately and you see 10 different searches?

What does your input folder look like? Mine is the torrent session folder so it's just a bunch of torrents named with their infohashes. Like `FF41FD3AF7FEEEDA5CD1D2F97FF2495CCD7F832C.torrent`

**Comment by Fiala06** [comment]
Thanks, yes this happened when running back-to-back and my input was my
.sessions folders .

I just tried it again and it had me update my config file. It's not doing
it anymore so guessing a change you made may have fixed it.

**Comment by mmgoodnow** [comment]
You might want to check out https://github.com/mmgoodnow/cross-seed/releases/tag/v1.7.0, it's got two new CLI flags you'd be interested in.
