### ISSUE TITLE
Switch cache to SQLite

### ISSUE THREAD

**Issue by Styloy** [mmgoodnow/cross-seed#202]
when I run the cross seed script with many/all indexers I notice massive amounts of slowdown and constant ~80mb/s disk writes.
when I run int verbose mode I can clearly see that making decisions takes about a second, this isn't surprising given my cache.json is 82.8mb on disk. 
I could clear this cache.. but there are some trackers that have a daily limit of how many .torrents you can download. I'd also be pulling a few thousand torrents down every time I did this.

to me this seems like it really should be moved to an sqlite database, it's just a lot of overhead to process a large json like this.

**Comment by mmgoodnow** [comment]
I've noticed this too. Migrating to SQLite is something I've had in mind for a while now, but it'll be a bit of an undertaking.

**Comment by nolemons** [comment]
Big +1 to this one, I see 40 MB/s average for 2 hours, which is not so great for the life of my poor ssd 😢

**Comment by mmgoodnow** [comment]
My bad, misclicked.

**Comment by jamiebegin** [comment]
Keep in mind that it's strongly recommended that SQLite DBs are *not* hosted off of NFS volumes. The lack of proper file locking will corrupt the DB. Moving in this direction might cause headaches for users.

**Comment by Randomblock1** [comment]
+1 to this.
I'm not sure why you would run cross-seed from a NFS volume, though. Either you run it alongside your torrent client, or you just run it elsewhere and inject it over the network or mount the torrent/output directory with NFS and have cross-seed read/write to it. 
A simple warning saying to not run cross-seed off NFS would probably suffice.

**Comment by mmgoodnow** [comment]
@jamiebegin I'm not really sure I can think of a valid use case for mounting the config for over nfs. Torrent dir and output dir, sure, but the config dir should be local. Can you elaborate on why you have it set up this way?

**Comment by mmgoodnow** [comment]
@Styloy @nolemons @Randomblock1 if you get the chance, please try out the `sqlite` branch, either with the `sqlite` docker tag, or by cloning the repo, checking out the branch, and using `npm link && npm link cross-seed`. It should
- automatically migrate your data from `cache.json` to `cross-seed.db`
- if successful, rename `cache.json` to `old-cache.json.bak`

**Comment by nolemons** [comment]
Sorry I didn't see the message, I updated my docker image to v4 and saw that the .db file got created and disk I/O was basically 0. Haven't done any crazy testing with it but so far it's been working fine for me!
