### ISSUE TITLE
What is the tornab URL syntax?

### ISSUE THREAD

**Issue by 07416** [mmgoodnow/cross-seed#206]
I can't figure out how to format the addresses in the `/.cross-seed/config.js` file. I've tried wrapping in quotes `""`, using the comma `,` or `\` as separator and get the `SyntaxError: Invalid or unexpected token` error with each attempt.

I copied the RSS feed as instructed in [the template](https://github.com/mmgoodnow/cross-seed/blob/master/src/config.template.cjs) and removed the presumably superfluous `&t=search&cat=&q=`string at the end.

Can you show an example with these URLs?

```
http://127.0.0.1:9117/api/v2.0/indexers/alpharatio/results/torznab/api?apikey=<personal-key>
http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd/results/torznab/api?apikey=<personal-key>
http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?apikey=<personal-key>
```

**Comment by 07416** [comment]
I found the answer [from here](https://github.com/mmgoodnow/cross-seed/pull/179#issuecomment-1004971494):
```
    torznab: [
    "http://127.0.0.1:9117/api/v2.0/indexers/alpharatio/results/torznab/api?apikey=<personal-key>",
    "http://127.0.0.1:9117/api/v2.0/indexers/beyond-hd/results/torznab/api?apikey=<personal-key>",
    "http://127.0.0.1:9117/api/v2.0/indexers/blutopia/results/torznab/api?apikey=<personal-key>",
],
```

**Comment by mmgoodnow** [comment]
In the future this would make a great discussion question! https://github.com/mmgoodnow/cross-seed/discussions

**Comment by djjoakim** [comment]
I can't get this to work.. i have been trying out different settings for the last hour but all i get is "SyntaxError: Unexpected token ':'" 
Can someone please help me?
What is wrong?

Here is my settings;

`module.exports = {
	/**
	 * @deprecated use torznab instead
	 */
	jackettServerUrl: "http://172.19.0.20:9117/",

	/**
	 * @deprecated use torznab instead
	 */
	jackettApiKey: "<myapi>",

	/**
	 * Pause at least this much in between each Jackett search. Higher is safer.
	 * 	It is not recommended to set this to less than 2 seconds.
	 */
	delay: 10,

	/**
	 * @deprecated use torznab instead
	 * Trackers to search
	 * Set to [] if you want to search all trackers.
	 * Tracker ids can be found in their Torznab feed paths
	 */
	trackers: [],

	/**
	 * List of Torznab urls.
	 * For Jackett, click "Copy RSS feed"
	 * For Prowlarr, click (i) and copy the Torznab Url, then append "?apikey=YOUR_PROWLARR_API_KEY"
	 */
		torznab: [
			"http://172.19.0.20:9117/api/v2.0/indexers/scenehd/results/torznab/api?apikey=<myapi>",
		],
	/**`

**Comment by mmgoodnow** [comment]
Does the syntax error come with a stacktrace? (Several lines starting with "at")?

One of the lines should have the path of your config file, along with the line number where the unexpected colon is.

**Comment by djjoakim** [comment]
Yep, i found the error...

i forgot to put "" over qbittorrentUrl: .

seems to start now, will see so the other functions work.
Thanks!
