### ISSUE TITLE
Allow Minimum Size for Search

### ISSUE THREAD

**Issue by Davo1624** [mmgoodnow/cross-seed#209]
It would be great to have a feature where you can search for all torrents that are above a certain file size (if possible).

For example, I would want to use the -a flag to search all torrents but I have a bunch of music torrents that I don't want to include in that search. If it was possible to set a minimum file size for cross-seed I could then search for all torrents but exclude ones under that minimum threshold.

**Comment by mmgoodnow** [comment]
good idea. at this point, several people have requested different custom prefilter conditions, bundled into #210
