### ISSUE TITLE
json submissions don't work the same as querystring.

### ISSUE THREAD

**Issue by KyleSanderson** [mmgoodnow/cross-seed#211]
`(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot use 'in' operator to search for 'infoHash' in { "name": "Dear.I.Shrunk.The.Kids" }`

It doesn't look like the in operator works with json in typescript (or atleast the returned type).

https://github.com/mmgoodnow/cross-seed/blob/4e1a1df189cd2bb9acb6f9ec56a0dc16c516b30e/src/server.ts#L32

**Comment by mmgoodnow** [comment]
Are you sure you're sending properly formatted JSON? I think it might be double-wrapped in quotes:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/9119498/159205249-62aa141c-698a-4df0-ab2b-418181dccf51.png">

**Comment by KyleSanderson** [comment]
My apologies, I was indeed sending garbage JSON. For completeness here's the patch for the other application to resolve the issue.

**Comment by KyleSanderson** [comment]
https://github.com/autobrr/autobrr/pull/189#issue-1174740534
