### ISSUE TITLE
Cross-seeds get stuck in radarr and sonarr queue

### ISSUE THREAD

**Issue by djjoakim** [mmgoodnow/cross-seed#230]
Hey!

I am running cross seed with qbittorrent in a docker, and it's working fine - the only problem i have is that everything that cross-seed inject to qbittorrent, also get injected in sonarr/radarr... and get's stuck in the queue since it's not an import..
Is there some solution to this?

Thanks!

![stuck](https://user-images.githubusercontent.com/77078108/164993919-4c600f5b-1b98-4058-8bc1-d5d99c77beb5.png)

**Comment by Jerrk** [comment]
It looks like you have everything under the same label?

i would suggest moving the torrents to a different label after they're completed and keep the cross seeded torrents in that label as well

![](https://i.imgur.com/CKhSjQU.png)

its under advanced settings in radarr/sonarr

**Comment by djjoakim** [comment]
> It looks like you have everything under the same label?
> 
> i would suggest moving the torrents to a different label after they're completed and keep the cross seeded torrents in that label as well
> 
> ![](https://camo.githubusercontent.com/a12bac5bf2557b197381a14bb11d090bb03f589d34db73a445a183de4e648d65/68747470733a2f2f692e696d6775722e636f6d2f434b68536a51552e706e67)
> 
> you need to enable advanced settings in radarr/sonarr to change this

Oh, i had no idea about this. I used "Category" but haven't set the Post-import. 
I have now changed it, does this auto-apply to cross-seed, or do i have to change something in the config.yml? 

Thanks!

**Comment by Jerrk** [comment]
It completely depends on how your cross seeds are added to qbittorrent such as maybe watch-folder or [injection](https://github.com/mmgoodnow/cross-seed/wiki/Injection)?

**Comment by djjoakim** [comment]
They use "injection" and u run the docker as deamon, so Radarr sends a trigger scrypt when a release is imported and updated, that sends a command to cross-seed

**Comment by djjoakim** [comment]
Works perfect now.. Thanks @Jerrk for the help :)
