### ISSUE TITLE
Log is full of [REDACTED]

### ISSUE THREAD

**Issue by rossdargan** [mmgoodnow/cross-seed#240]
every character in the log has [REDACTED] between it making it a pain in the ass to figure out whats going on. I'm running in daemon mode in docker if that helps!

Script is fab apart from that though!

**Comment by mmgoodnow** [comment]
Please show an example

**Comment by rossdargan** [comment]
This is from info.current.log, but the docker log shows the same. Replacing [REDACTED] with nothing obviously makes it readable, and it looks like this:

> 2022-05-11 10:03:39 [32minfo[39m: Validating your configuration...
2022-05-11 10:03:39 [31merror[39m: Torznab url http://192.

Original:

> 2022-05-11 10:03:39 [32minfo[39m: V[REDACTED]a[REDACTED]l[REDACTED]i[REDACTED]d[REDACTED]a[REDACTED]t[REDACTED]i[REDACTED]n[REDACTED]g[REDACTED] [REDACTED]y[REDACTED]o[REDACTED]u[REDACTED]r[REDACTED] [REDACTED]c[REDACTED]o[REDACTED]n[REDACTED]f[REDACTED]i[REDACTED]g[REDACTED]u[REDACTED]r[REDACTED]a[REDACTED]t[REDACTED]i[REDACTED]o[REDACTED]n[REDACTED].[REDACTED].[REDACTED].
2022-05-11 10:03:39 [31merror[39m: T[REDACTED]o[REDACTED]r[REDACTED]z[REDACTED]n[REDACTED]a[REDACTED]b[REDACTED] [REDACTED]u[REDACTED]r[REDACTED]l[REDACTED] [REDACTED]h[REDACTED]t[REDACTED]t[REDACTED]p[REDACTED]:[REDACTED]/[REDACTED]/[REDACTED]1[REDACTED]9[REDACTED]2[REDACTED].[REDACTED]

**Comment by mmgoodnow** [comment]
Do you have an empty Jackett api key? If so, this is fixed by #246

**Comment by mmgoodnow** [comment]
gonna close this, lmk if it's still happening on v4
