### ISSUE TITLE
fuzzy name searching when trying to reverse lookup from announce

### ISSUE THREAD

**Issue by KyleSanderson** [mmgoodnow/cross-seed#241]
Cross-seed in daemon mode is an excellent solution to reducing system load and latency for adding files to the client of your choice. The issue that I'm coming up against is the source strings submitted aren't matching the file names in the client. This is because there's a file extension on the name, the announce is mangled by changing periods to spaces, capitalization, etc. This is resulting in cross-seed not finding the entry in the client, and moving on.

**Comment by mmgoodnow** [comment]
They don't lookup by filename, they look up by torrent name. Can you give more detail?

**Comment by KyleSanderson** [comment]
The announce comes in as `Sopranos S02 1080p BluRay x264-Group`. The file has it as `The.Sopranos.S02.1080p.BluRay.x264-Group` which results in no match.

**Comment by mmgoodnow** [comment]
I apologize if the following sounds harsh; I do not mean it in a harsh way. 

You're making assumptions about how cross-seed works and jumping to conclusions which is making it harder to debug this problem. For me to best help, can you lay out the _facts_ of the entire situation please?

**Comment by KyleSanderson** [comment]
> I apologize if the following sounds harsh; I do not mean it in a harsh way.

All good, I appreciate getting to the bottom of something quickly 😄 

I've sent a log on Discord, even the exact name match (copied from qBittorrent directly) does not find the torrent in the client. Searching the infoHash surprisingly finds it, and gives an injection.

**Comment by KyleSanderson** [comment]
Is there any additional information I can provide?

**Comment by KyleSanderson** [comment]
Highlighting the exact issue from Discord from a week ago.

As detailed in https://github.com/mmgoodnow/cross-seed/pull/212#issuecomment-1075710542

The step of 
```
Indexes torrentDir
check for torrent in dir with same name as announced
run match/decision logic
```

does not work with single file torrents that have directories created in qBittorrent. The session name for the torrent will have the filename, ending typically in .mkv, and the client + announce that goes out never has the extension. This is detailed well in https://github.com/mmgoodnow/cross-seed/blob/dcb3809770569d4641a4211e6e42e5d0e2417634/src/torrent.ts#L156 

Extensions are particularly finicky, and as such the code here strips them before searching torznab because there's no expectation of this being searchable on sites. https://github.com/mmgoodnow/cross-seed/blob/dcb3809770569d4641a4211e6e42e5d0e2417634/src/pipeline.ts#L183

The enhancement here can be in this function to also pull the names of the torrents in the client https://github.com/mmgoodnow/cross-seed/blob/689b5a382eaa44b540a302b56961a5b676d4c2b9/src/torrent.ts#L96

Anyway, you know the code best, and the example of the problem is on discord.

**Comment by mmgoodnow** [comment]
Looking at it now

**Comment by mmgoodnow** [comment]
So I think the nuance here lies in the difference between the torrent name and the release name. The API in #212 requires the torrent name (which usually has an extension for a single file torrent but not for a multi-file torrent) not the release name. 

I'm assuming you're using autobrr; is there any way you can access the _torrent_ name to pass that to cross-seed? Or does that data just not exist on announces? cc @ludviglundgren

**Comment by mmgoodnow** [comment]
If it doesn't exist on most announces, I'd consider doing the fuzzy match. But I only really want to do that as a last resort.

**Comment by KyleSanderson** [comment]
The data does not exist on announces unfortunately, and is inconsistent. Additionally some trackers replace periods with spaces on announce, or have garbage strings like `Bloodthirsty [2020] - BdC` as the string for a very different torrentname.

I'm still using the webhook api fwiw.

**Comment by ludviglundgren** [comment]
Kyle is correct, autobrr doesn't parse the content in the actual torrent file, unless it's later in the filtering and only for size when it's not announced or no api implemented for that tracker.

I still haven't gotten to implementing the announce to cross-seed.

**Comment by mmgoodnow** [comment]
damn that's unfortunate. Fuzzy string matching is a bit of a hard problem to solve, so I'll have to think on this for a bit.
