### ISSUE TITLE
If source torrent comes from Deluge (/state folder), created torrent fails to inject into QBittorrent

### ISSUE THREAD

**Issue by wtouchstone** [mmgoodnow/cross-seed#259]
Not sure if this is an expected outcome, but I've finally isolated the issue of why my torrent injects are failing in some cases and not in others.

If a .torrent file is pulled from the QBittorrent BT_backup directory, it can be searched, found, and injected without issue. However, I also have torrents that come from Deluge (both manually added, and through radarr). When I copy these and cross seed them, they fail to inject. 

This might be a directory issue, but IDK how cross-seed works. I set the default download folder on QB to match the location of the Deluge torrents, however they still fail to inject. My workflow is setup so that items from radarr/sonarr from public trackers go to deluge and privates to qb (to permaseed). Considering I can drag and drop the output files and it works fine, I'm not sure why injecting here doesn't work.

I wish I could provide more log info, but all I get even in verbose is "xx failed to inject, saving instead"

**Comment by mmgoodnow** [comment]
Unfortunately cross-seeds must be injected into the same client they came from.
