### ISSUE TITLE
Make HTTP server optional

### ISSUE THREAD

**Issue by Byter09** [mmgoodnow/cross-seed#263]
Before, I never really had a use for `daemon` mode and always "manually" looped `cross-seed`. Now, with v4, I finally have a reason to use this mode by activating the RSS and search feature.

However, the daemon always starts a HTTP server. In my environment this is not a problem, I simply don't expose the port, but I suspect there are other situations I can't even come up with, in which this isn't a good thing. So, if a user simply wants to use RSS and periodic search in `daemon` mode, they currently _have_ to have this HTTP server running.

I propose, now that daemon mode has more than just one feature, to make this HTTP server optional.

Thanks for v4 though. Love the new features :D

**Comment by mmgoodnow** [comment]
v4.2.0
