### ISSUE TITLE
Migration guide is wrong

### ISSUE THREAD

**Issue by Byter09** [mmgoodnow/cross-seed#265]
Hi. I followed the [migration guide](https://github.com/mmgoodnow/cross-seed/wiki/v4-Migration-Guide) to get my `config.js` up-to-date.

Turns out that the guide mentions `allowNonVideos` as a replacement for `searchAll`. This, according to the template in the repository, should say `includeNonVideos` though.

`cross-seed` did not search over half of my torrents because I used the wrong parameter and it thus assumed a default of `false`.

I recommend updating the guide ASAP, or maybe even go as far as allowing `allowNonVideos` as a secondary hidden parameter for those that already put this in their config. Unsure if that's a lot of people though, so a simple guide edit should do the trick. :D

**Comment by mmgoodnow** [comment]
Thanks, good catch!
