### ISSUE TITLE
cross-seed doesn't exit on startup validation failure

### ISSUE THREAD

**Issue by ayazgoff** [mmgoodnow/cross-seed#277]
**Current behavior:** If cross-seed is started before the torznab service, it will log an error, but continue running:
```
# docker container logs -f cross-seed_cross-seed.1.bmpj5qcn7y3r1kgk9i9erqxam
Configuration file already exists.
info: Validating your configuration...
warn: Failed to reach http://prowlarr_prowlarr:9696/1/api?apikey=[REDACTED]
error: no working indexers available
```
**Desired behavior:** The main process should exit with failure status. This way the container will die and, if running in Swarm mode, automatically be recreated until the torznab service is healthy.

**Comment by mmgoodnow** [comment]
you're right, I think this is a regression.

**Comment by KyleSanderson** [comment]
I'm seeing the same behaviour.

**Comment by mmgoodnow** [comment]
v4.1.1
