### ISSUE TITLE
result is not iterable 

### ISSUE THREAD

**Issue by skels130** [mmgoodnow/cross-seed#280]
When trying to run this, I get the following output in the log, and it crashes. Ideas?

2022-07-15 18:29:46 [36mverbose[39m: [rtorrent] Calling method download_list with params []
2022-07-15 18:29:46 [36mverbose[39m: [rtorrent] Calling method system.multicall with params [ [ { methodName: 'd.is_multi_file',
      params: [ '13C342B145CBC1D025756677D5674A16D4BE9046' ] },
    { methodName: 'd.directory',
      params: [ '13C342B145CBC1D025756677D5674A16D4BE9046' ] },
    { methodName: 'd.complete', params: [ '13C342B145CBC1D025756677D5674A16D4BE9046' ] } ] ]
2022-07-15 18:29:46 [31merror[39m: result is not iterable

**Comment by skels130** [comment]
I missed fixing a config. This is likely all my fault.

**Comment by mmgoodnow** [comment]
What was the config?

**Comment by skels130** [comment]
I was in the process of both updating configs to v4 and migrating from qbittorrent to rutorrent. I had fixed the docker parameters for the daemon container I run, but not the normal version that runs on a schedule. I still had the "/torrents" input pointed at the qbittorrent directory rather than the new rtorrent directory.
