### ISSUE TITLE
Doesn't seem to be respecting exclude recent search value. 

### ISSUE THREAD

**Issue by skels130** [mmgoodnow/cross-seed#284]
```
	// directory containing torrent files.
	// For rtorrent, this is your session directory
	// as configured in your .rtorrent.rc file.
	// For deluge, this is ~/.config/deluge/state.
	// Don't change this for Docker.
	// Instead set the volume mapping on your docker container.
	torrentDir: "/torrents",

	// where to put the torrent files that cross-seed finds for you.
	// Don't change this for Docker.
	// Instead set the volume mapping on your docker container.
	outputDir: "/cross-seeds",

	// Whether to search for single episode torrents
	includeEpisodes: true,

	// search for all torrents, regardless of their contents
	// this option overrides includeEpisodes.
	//searchAll: true,
	includeEpisodes: true, 
	includeNonVideos: true,
	// Exclude torrents first seen more than n minutes ago.
	excludeOlder: undefined,

	// Exclude torrents which have been searched
	// more recently than n minutes ago.
	excludeRecentSearch: "7200min",
        //I've also tried "7200 minutes" in the line above. 

	// can be either "save" or "inject".
	// With "inject" you need to set up one of the below clients.
	action: "inject",
```
Here is the snippet from my config. The format seems to be correct for the property. Anyone have an idea?

**Comment by mmgoodnow** [comment]
What behavior are you experiencing?

**Comment by skels130** [comment]
When running the script, it searches all torrents regardless of last search time. I've got around 2400, so that causes the script to run for extended periods.

**Comment by mmgoodnow** [comment]
what do the permissions on your config directory look like?

**Comment by skels130** [comment]
```
# ls -ld config
drwxrwxrwx 1 99 users 172 Jul 18 08:11 config
# cd config
# ls
config.js  cross-seed.db  cross-seed.pre-jobs.backup.db  logs  old-cache.bak.json  torrent_cache
# ls -la
total 37952
drwxrwxrwx 1   99 users      172 Jul 18 08:11 .
drwxr-xr-x 1 root root       202 Jul 15 18:36 ..
-rw-rw-rw- 1   99 users     3049 Jul 17 13:24 config.js
-rw-r--r-- 1 root root  11788288 Jul 18 08:11 cross-seed.db
-rw-r--r-- 1 root root   9801728 Jun 17 04:40 cross-seed.pre-jobs.backup.db
drwxr-xr-x 1 root root      2262 Jul 18 04:40 logs
-rw-r--r-- 1 root root  17266454 Jun 16 04:43 old-cache.bak.json
drwxr-xr-x 1 root root     73700 Jul 17 23:55 torrent_cache
```

I wouldn't think it would be a permissions issue as I'm running the docker image.

**Comment by mmgoodnow** [comment]
If you run these commands, what shows up?
```shell
$ sqlite3 cross-seed.db
> select count(*), first_searched, last_searched from searchee group by (first_searched is null) (last_searched is null);
```

**Comment by skels130** [comment]
It gave me a syntax errror: Error: near "(": syntax error

And my SQL is not near good enough to know whats wrong there.

**Comment by mmgoodnow** [comment]
hm, that means that all of your torrents have recorded timestamps.

is the `info: [search] Found X torrents, Y suitable to search for matches` log the same if you use `excludeRecentSearch: "52 weeks",` (an arbitrarily high number) vs `excludeRecentSearch: "1 minute",`?

**Comment by skels130** [comment]
As far as I can tell, yes. However, I am testing a theory currently, so I'm going to wait a while to give a firm answer. I've tweaked some settings, and I'm letting it run now, to see if it was possibly an exit issue. I'm not sure if it writes the information to the DB as it scans, or at the end.

**Comment by mmgoodnow** [comment]
It writes to the DB after it has performed its search and assessed all the results.

**Comment by mmgoodnow** [comment]
Glad you were able to get to the bottom of it! You're far from the only person to report this so thanks for letting us know what the problem ended up being. Did you set up your unraid container based on a guide?
