### ISSUE TITLE
Add a healthcheck to the docker container

### ISSUE THREAD

**Issue by Steve-Brule** [mmgoodnow/cross-seed#285]
An ability to restart the container if "error: no working indexers available" comes up would also be highly useful.

My use case for this is as follows: when booting up my machine, sometimes cross-seed happens to start before prowlarr does. Cross-seed checks for the configured prowlarr api URLs, those don't work yet and cross-seed fails. It remains in a failed state until I notice that it has failed and restart it manually.

**Comment by mmgoodnow** [comment]
Dupe of #277?
