### ISSUE TITLE
Option to clear the cache

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#37]
I read in an issue here that the user should clear the cache.  It's not stated in the instructions how to do that.  Also an option `--clear-cache` should be created.

**Comment by mmgoodnow** [comment]
`cross-seed --help` will show you the way. I'll see if I can add it to the README.

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/releases/tag/v1.10.4
