### ISSUE TITLE
The additional help that's listed in the config file would be helpful to have listed in the README.md instructions

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#40]
For example, `// Tracker ids can be found in their Torznab feed paths` would be nice to have listed in the README.md instructions since not every one will use the config file.  And for this example, a user wouldn't know whether to use `Beyond-HD (OneURL)` or `beyond-hd-oneurl` in the command line switch.

Similarly, all the other additional info listed in the config file would be helpful to have listed in the README.md too

**Comment by mmgoodnow** [comment]
https://github.com/mmgoodnow/cross-seed/releases/tag/v1.10.4
