### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Drazzilb08** [mmgoodnow/cross-seed#46]
So I've ran into a issue with a couple of torrents that just will not recheck in my client, even though every aspect of the two torrents line up (or at least from what I can see).

 Instead of banging my head against a table to try to figure every torrent that just won't force check. 
Would there be a possible way to black list a certain release as opposed to just removing every time the script cycles through?

**Comment by mmgoodnow** [comment]
I might be able to work something out, but it's also very important to me that cross-seed produces no false-positives. Is there any chance you could send me the offending torrents for inspection? If you use *nix you can edit out your passkey fairly easily with vim.

I understand if you don't want to do that but it would really be invaluable for tracking down this bug.

**Comment by mmgoodnow** [comment]
Additionally, seeing a mediainfo dump for any particular files that fail the recheck would be very helpful as well.

Here are a couple other questions:
- What's the scale of this problem? Is it just one torrent, two, ten?
- If it's multiple, are they all on the same tracker?
- maybe they have embedded subtitles of a different language?
- How many files fail to recheck? Which ones?

**Comment by Drazzilb08** [comment]
> * What's the scale of this problem? Is it just one torrent, two, ten?: The scale of the problem is quite small (which is a testament to the script). I don't remember how many. there were, I've removed them before I thought about making a GHI out of it.

> * If it's multiple, are they all on the same tracker? I'll get back to you on this one.

> * maybe they have embedded subtitles of a different language? I'll have to check for you.

> * How many files fail to recheck? Which ones?

At the end of all of it I'll let another full cycle run through and get back to you with more details.

**Comment by Drazzilb08** [comment]
Okay so I let it go for a while (over night). So far I have 3 (out of my massive amount thats quite impressive for such a low number). However, one thing they have in common are:
1. From the same tracker: BHD
2. Season packs
3. 2 out of the 3 are from the same release group BTN of the same show. (other one is DON for a different show)
4. DON will check up to 36%
....
So I figured out what the main difference between the two BTN torrents are. 
In the folder structure the sub-folder of the original was `_` <-- just that
In he folder structure of the cross seed it has the release name
Cross-seed
Property.Brothers.S04.720p.WEB-DL.AAC2.0.h.264-BTN
|__ Episodes

Original 
Property.Brothers.S04.720p.WEB-DL.AAC2.0.h.264-BTN
|__ _
     |__Episodes

...
For the DON release 
Here is a paste of the media info
https://paste.ubuntu.com/p/hnypBkBjT5/

As far as something to edit the torrent file you mentioned VIM or *NIX. I'm not familiar with these softwares.

**Comment by Drazzilb08** [comment]
After inspection between the two files the difference between them are 
Original
---
```
  "info": {
      "files": [
         {
            "length": 1422982369,
            "path": [
               "",
               "Property.Brothers.S05E10.Stephan.and.Karina.720p.WEB-DL.AAC2.0.h.264-BTN.mkv"
            ]
         },
```

and

Cross-Seed
---

```
   "info": {
      "files": [
         {
            "length": 1422982369,
            "path": [
               "Property.Brothers.S05E10.Stephan.and.Karina.720p.WEB-DL.AAC2.0.h.264-BTN.mkv"
            ]
         },
```

Now I see where the `_` is coming from

**Comment by mmgoodnow** [comment]
Wow, that is a _huge_ find. Thank you so much for your help debugging! I'll definitely be able to fix that.

**Comment by mmgoodnow** [comment]
Ok, I just pushed a tentative fix in version 2.0.2. Would you mind running it again on the new version?

**Comment by Drazzilb08** [comment]
Can you push that to Docker. As this is how I'm running the script. Then I'll gladly let it run through and see if its comes back.

**Comment by Drazzilb08** [comment]
Can you push that to docker when you get a chance.

**Comment by mmgoodnow** [comment]
Whoops, the docker builds started failing because of my fix. Try `version-2.0.5` or `latest` now.

**Comment by Drazzilb08** [comment]
Been running it for a couple days now. Havn't noticed that issue come back.  

I'm going to consider this closed.

**IF** I do I'll reopen this issue, and let you know
