### ISSUE TITLE
Script was running fine but now getting errors

### ISSUE THREAD

**Issue by M3Element** [mmgoodnow/cross-seed#47]
I finally had the script running and was trying to test some torrents. Later in the day I tried again but I am now getting errors and I didn't change anything on my end that I can think of. This is the result if I try to run the cross-seed app.

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/mmgoodnow/parse-torrent.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-04T14_49_05_477Z-debug.log
Install for [ 'cross-seed@latest' ] failed with code 254

* Any help would be greatly appreciated. I am quit the novice with all of this so bare with me.

**Comment by mmgoodnow** [comment]
Sorry about that, it's my fault not yours. I'll have it fixed shortly

**Comment by M3Element** [comment]
Ah thank you for the quick reply. I thought for sure I must have done something on my end and was racking my brain as to what it could have been.

**Comment by mmgoodnow** [comment]
Should be fixed now, let me know if you have any more problems!

**Comment by M3Element** [comment]
Hey I do have another question. Ive been trying to run some cross seed tests with torrents I know are on two different trackers but no matter what I cant get a match even though the torrents and files are the same. I had someone else do a test using a torrent  from one tracker and match with another and theirs came back as a match. I then tried the exact same file from the same tracker they snatched it from and tried to match it with the same tracker they also used, but my results came back with no match. I have screenshots of both their results and mine but wasn't sure if I should post them.

**Comment by mmgoodnow** [comment]
@M3Element did you have another problem? If so please open a new issue

**Comment by M3Element** [comment]
Hey sorry, I was having a separate issue that fixed itself so I deleted my initial post shortly after posting it.
