### ISSUE TITLE
Node out of memory

### ISSUE THREAD

**Issue by Drazzilb08** [mmgoodnow/cross-seed#48]
https://paste.ubuntu.com/p/NrTC7rrJ8g/

So I was checking on things and noticed this in the logs as well as the container not running when it should have been.

If you require a larger paste let me know I'll snag that for you.

Note: running `:latest`

**Comment by mmgoodnow** [comment]
When you run `cross-seed search` it will load all of the torrent files into memory. 

Since you're running it on ~7000 torrents the process is hitting its memory limit. If you assume an average torrent size of 100 kB, that means that all of the torrents loaded into memory will take roughly 700 MB, which, coincidentally, is the default max heap size of a Node process. 

I can make some optimizations to have the process use less memory but it might take a couple weeks. In the meantime, I think you can set the `NODE_OPTIONS` environment variable to something like `--max-old-space-size=2048` which will allocate up to 2GB of memory towards `cross-seed`, but never more than it needs. If you're in a memory-constrained environment you may not want to do this but it's an easy temporary fix.

Let's talk about your use case for a bit. I saw your `cross-seed-guide` repo and it looks like you're running `cross-seed search` with cron. That's fine but it was not really designed to be used like this - it loads all torrents into memory, and it hammers all of your trackers with search requests every run. If you run it daily it will search all trackers for all torrents every day. With 7000 torrents and 20 trackers that's 140,000 searches a day. (though it's not quite that bad if you use the --exclude-recent-search option)

What is your ideal solution here? Clearly you are a power user and I'd like to help out. I'd like to make daemon mode solve for your use-case.

**Comment by Visorask** [comment]
I am one of the dev's for https://github.com/StuffAnThings/qbit_manage. 

We are basically using your outputs to inject into qbit. But at the moment your daemon mode only supports rtorrent. 

So basically the goal is to search any torrents as they come in and are completed downloading (daemon mode would be nice) and inject them into qbittorrent with the proper category, tag. Honestly a daemon mode that can detect when a torrent is done in qbit, search it and put it into a folder as is now would make the memory issue go away and cause less searches for trackers at once. 

My script could do the rest of the work just fine it's just the initial search being able to tell when a torrent is in qbit and finished downloading.

**Comment by mmgoodnow** [comment]
What does your script do @Visorask?

**Comment by mmgoodnow** [comment]
I'm definitely willing to add qbit integration if you can help me out a bit

**Comment by Drazzilb08** [comment]
That would be great. I've been working with visorask with the qbit manager script hence the guide I made more of notes for my self on how I have everything all set up and maybe help somebody else out.  

But in regards to the end goals he can articulate those much better than I can as he is a coder and I am not. Hence maybe things not being quite optimized on my end. 

With regards to running search for the argument. I do understand this would cause a TON of search queries. This is why I use the exclude recent search option. 

I will add that environment variable in this evening and report back.

**Comment by Visorask** [comment]
Basically at the moment it does quite a bit outside the scope of your script. But the functionality of adding onto your script is this:
```
1. Takes the .torrents your script creates and matches them with a torrent already there.
2. It then grabs the category/save_path of the already existing torrent and tacks it onto the injected torrent, so there is no accidental wrong save_path or category when importing. It adds these torrents as paused just in case there is something wrong with the torrent or something got into the import folder that is not supposed to be there.
3. The script then does a check of all paused torrents and if the progress is == 0 (0%) then we start the torrent to start checking.
4. It also does a check to see if torrent progress == 1 (100%) it will resume that torrent to start seeding. 
```
That's the gist of it. I was also toying with the idea of adding some kind of check as RSS doesn't populate immediately, adding the torrent to a DB or list of some kind and checking it after like a 15-20 minute delay to hopefully grab every torrent.

As far as integrating with qbit it's pretty easy as there API is pretty well outlined, I use the python wrapper but here is the API for qbit: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)

Most of my calls in my code can basically be re-used just with the url version of API.

If there is any questions let me know.

**Comment by Drazzilb08** [comment]
> I can make some optimizations to have the process use less memory but it might take a couple weeks. In the meantime, I think you can set the `NODE_OPTIONS` environment variable to something like `--max-old-space-size=2048` which will allocate up to 2GB of memory towards `cross-seed`, but never more than it needs. If you're in a memory-constrained environment you may not want to do this but it's an easy temporary fix.

This worked as intended. I'll let you two work on a much more elegant solution for this and qbit. I'm always down for testing and helping out as I run across these issues. 

I have a large pool to work with (client shows 7105 torrents loaded into it as writing this) across 7 different trackers that I seed to and I'm constantly adding things. 

Thank you very much for your quick replies and help also for writing an amazing script (as well as wrapping it into a container for us using docker)

**Comment by Drazzilb08** [comment]
> I can make some optimizations to have the process use less memory but it might take a couple weeks. In the meantime, I think you can set the `NODE_OPTIONS` environment variable to something like `--max-old-space-size=2048` which will allocate up to 2GB of memory towards `cross-seed`, but never more than it needs. If you're in a memory-constrained environment you may not want to do this but it's an easy temporary fix.

This worked as intended (had to bump to 3GB of memory out of my 32GB available). I'll let you two work on a much more elegant solution for this and qbit. I'm always down for testing and helping out as I run across these issues. 

I have a large pool to work with (client shows 7105 torrents loaded into it as writing this) across 7 different trackers that I seed to and I'm constantly adding things. 

Thank you very much for your quick replies and help also for writing an amazing script (as well as wrapping it into a container for us using docker)

**Comment by mmgoodnow** [comment]
Glad to give to the community. 😄 I hope to eventually bring automatic cross-seeding to the masses. It will improve retention across the board and hopefully promote single-file torrents without extra crap in them lol. 

And I'm glad that you're getting value out of it! User engagement is a huge motivator for me to continue to work on `cross-seed` and make it better.

**Comment by Drazzilb08** [comment]
I'm glad to hear that. 

I'll consider my issue closed on this one as the temp fix is working just fine right now. I'll await whatever is concocted to better support my use case.

**Comment by mmgoodnow** [comment]
The latest release, v2.2.1, has a huge improvement in memory footprint, in addition to some caching improvements. I saw a drop from 1.15 GB to 240 MB in cross-seed's memory usage in one of my tests (with around 1800 torrents loaded). So the next time you update, I think you probably won't need the extra node heap space any more. 

qBittorrent support is on the way! You can check out the development roadmap here: https://github.com/mmgoodnow/cross-seed/projects/1
