### ISSUE TITLE
Last update has stopped respecting listed trackers in config

### ISSUE THREAD

**Issue by DuzAwe** [mmgoodnow/cross-seed#5]
Last update has stopped respecting listed trackers in config

**Comment by mmgoodnow** [comment]
I’ll check it out

**Comment by mmgoodnow** [comment]
ok, should be good now. I removed my axios dep to replace it with a smaller package but it seems like the query params don't stringify in the same way. 

https://github.com/mmgoodnow/cross-seed/commit/22fe60b4cc2d0b6d34fc0d5c7d05bd95cf6b6fe0
