### ISSUE TITLE
Running npx cross-seed search command throws an error.

### ISSUE THREAD

**Issue by hawkinspaul** [mmgoodnow/cross-seed#56]
Error: https://pastebin.com/QMR8raTc
I'm not sure what I'm doing wrong. It's worked in the past but suddenly it stopped working. Any help is appreciated.

**Comment by mmgoodnow** [comment]
It looks like you've got a corrupted torrent file. I'll add a fix this weekend to skip over those!

**Comment by hawkinspaul** [comment]
That makes a lot of sense. Thanks! Looking forward to it.

**Comment by mmgoodnow** [comment]
Didn't get to it this weekend, hoping to push a fix later today though.

**Comment by mmgoodnow** [comment]
This should be fixed as of [`v2.3.2`](https://github.com/mmgoodnow/cross-seed/releases/tag/v2.3.2). 

Please feel free to reopen if the problem persists!

By the way, sometimes it's tricky updating when you're using npx, so make sure you're running 2.3.2 with `npx cross-seed --version`

**Comment by hawkinspaul** [comment]
Brilliant! Thanks again, it's a fantastic tool.
