### ISSUE TITLE
cross-seed autotorrent

### ISSUE THREAD

**Issue by scr44tch** [mmgoodnow/cross-seed#6]
hi,
no issue here, i just wanted to ask you if you would share your autotorrent.conf

i find more and more torrents saved by cross-seed,
that would not be imported by autotorrent. 
Missing files, only 0.00% found (xx GB missing)

when i add them manually they recheck just fine.
i use scan_mode = unsplitable,normal,hash_size

any help appreciated

**Comment by mmgoodnow** [comment]
You might need to rebuild your auto torrent database with -r. I use “exact” and it still works.

Sent from my iPhone

On Jun 24, 2020, at 15:38, scr44tch <notifications@github.com> wrote:

﻿

hi,
no issue here, i just wanted to ask you if you would share your autotorrent.conf

i find more and more torrents saved by cross-seed,
that would not be imported by autotorrent.
Missing files, only 0.00% found (xx GB missing)

when i add them manually they recheck just fine.
i use scan_mode = unsplitable,normal,hash_size

any help appreciated

**Comment by mmgoodnow** [comment]
also, cross-seed does not do any validation to make sure that the torrents are done. It just assumes every torrent in the directory is already seeding. 

Let me know if this helps so I can close the issue.
