### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by bjeanes** [mmgoodnow/cross-seed#7]
```
Found 40 torrents, 4 suitable to search for matches
[1/4] Searching for Silicon.Valley.S01.1080p.Bluray.HEVC.FLAC.x265.5.1-Absinth
(node:18) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /usr/local/lib/node_modules/cross-seed/node_modules/simple-get/index.js:85:23
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cross-seed/node_modules/simple-concat/index.js:7:13)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1226:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am not sure what the JSON is that it is trying to parse, but presumably a response from Jackett...

Any idea what this might be?

I looked at the source and manually ran the request it appears to run, and it shows valid JSON:

``` sh-session
$ curl -i "https://REDACTED/api/v2.0/indexers/all/results?apikey=REDACTED&Query=silicon%20valley%20s01&Tracker[]=milkie&Tracker[]=aither&Tracker[]=digitalcore"
{"Results":[{"FirstSeen":"0001-01-01T00:00:00","Tracker":"Aither","TrackerId":"aither","CategoryDesc":"TV","BlackholeLink":null,"Title":"Silicon Valley S01 1080p Bluray HEVC FLAC x265 5.1-Absinth","Guid":"https://aither.cc/torrents/597","Link":"REDACTED","Comments":"https://aither.cc/torrents/597","PublishDate":"2020-06-07T11:34:56.8318653+10:00","Category":[5000,100002],"Size":11639361536,"Files":null,"Grabs":26,"Description":null,"RageID":null,"TVDBId":null,"Imdb":null,"TMDb":null,"Seeders":7,"Peers":0,"BannerUrl":null,"InfoHash":null,"MagnetUri":null,"MinimumRatio":1.0,"MinimumSeedTime":172800,"DownloadVolumeFactor":1.0,"UploadVolumeFactor":1.0,"Gain":75.88000106811523},{"FirstSeen":"0001-01-01T00:00:00","Tracker":"DigitalCore","TrackerId":"digitalcore","CategoryDesc":"TV/HD","BlackholeLink":null,"Title":"Silicon Valley S01 720p BluRay DD5.1 x264-EbP","Guid":"https://digitalcore.club/torrent/112358/","Link":"REDACTED","Comments":"https://digitalcore.club/torrent/112358/","PublishDate":"2020-03-22T21:02:43+11:00","Category":[5040,100012],"Size":14720098328,"Files":9,"Grabs":14,"Description":"Title: Silicon Valley<br>\nYear: 2014<br>\nGenres: Comedy<br>\nTagline: Follows the struggle of Richard Hendricks, a Silicon Valley engineer trying to build his own company called Pied Piper.<br>\nCast: Thomas Middleditch, T.J. Miller, Josh Brener, Martin Starr<br>\nRating: 8<br>\nTags: P2P<br>\nPre: 0000-00-00 00:00:00<br>\nSection: archive","RageID":null,"TVDBId":null,"Imdb":2575988,"TMDb":null,"Seeders":2,"Peers":0,"BannerUrl":"https://digitalcore.club/img/imdb/tt2575988.jpg","InfoHash":null,"MagnetUri":null,"MinimumRatio":1.1,"MinimumSeedTime":172800,"DownloadVolumeFactor":1.0,"UploadVolumeFactor":1.0,"Gain":27.41831974685192},{"FirstSeen":"0001-01-01T00:00:00","Tracker":"DigitalCore","TrackerId":"digitalcore","CategoryDesc":"TV/HD","BlackholeLink":null,"Title":"Silicon.Valley.S01-S05.480p.BluRay.WEBRip.nSD.x264-NhaNc3","Guid":"https://digitalcore.club/torrent/93230/","Link":"REDACTED","Comments":"https://digitalcore.club/torrent/93230/","PublishDate":"2019-11-18T13:33:20+11:00","Category":[5040,100012],"Size":18025575945,"Files":46,"Grabs":14,"Description":"Title: Silicon Valley<br>\nYear: 2014<br>\nGenres: Comedy<br>\nTagline: Follows the struggle of Richard Hendricks, a Silicon Valley engineer trying to build his own company called Pied Piper.<br>\nCast: Thomas Middleditch, T.J. Miller, Josh Brener, Martin Starr<br>\nRating: 8<br>\nTags: P2P<br>\nPre: 0000-00-00 00:00:00<br>\nSection: archive","RageID":null,"TVDBId":null,"Imdb":2575988,"TMDb":null,"Seeders":2,"Peers":0,"BannerUrl":"https://digitalcore.club/img/imdb/tt2575988.jpg","InfoHash":null,"MagnetUri":null,"MinimumRatio":1.1,"MinimumSeedTime":172800,"DownloadVolumeFactor":0.0,"UploadVolumeFactor":1.0,"Gain":33.575251596048474}],"Indexers":[{"ID":"aither","Name":"Aither","Status":2,"Results":1,"Error":null},{"ID":"digitalcore","Name":"DigitalCore","Status":2,"Results":2,"Error":null},{"ID":"milkie","Name":"Milkie","Status":2,"Results":0,"Error":null}]}
```

It might be good to catch an exception on each torrent processed so it continues with the rest, because currently it tanks all 4 matches.

Also, I am unclear why it's only matching 4 of the torrents as potential files.

Side-note: any reason cross-seed is limited to `.mkv`s?

**Comment by mmgoodnow** [comment]
Interesting. I did some digging and it looks like the newlines are malformed. 
JSON string literals need to be double-escaped because JSON itself is a string format. I'll see what I can do to clean it.

This is valid JSON:
```
"\\n"
``` 
This is invalid JSON:
```
"\n"
```
The `\n` gets parsed into a line feed character `0x0A` when reading the byte stream into a string. Then, the JSON parser encounters the LF character and chokes. 

> Also, I am unclear why it's only matching 4 of the torrents as potential files.
Big culprit could be NFOs. I designed cross-seed to be very aggressive in its pre-filtering, both to prevent hammering the trackers unnecessarily, and because I didn't want to deal with extra bs files and the symlinks they require. Movie torrents will likely only be eligible if they only include a single file. 

The cross-seeding is limited to `.mkv`s mostly because that fits my personal workflow best, I only have `.mkv`s. But I could easily be persuaded to allow `.mp4` and `.avi`.

**Comment by bjeanes** [comment]
> The `\n` gets parsed into a line feed character `0x0A` when reading the byte stream into a string. Then, the JSON parser encounters the LF character and chokes.

good catch! That sounds like it is potentially a Jackett bug then, right?

> Big culprit could be NFOs. I designed cross-seed to be very aggressive in its pre-filtering

Fair enough. 

> The cross-seeding is limited to `.mkv`s mostly because that fits my personal workflow best, I only have `.mkv`s. But I could easily be persuaded to allow `.mp4` and `.avi`.

Cool, thought so. Most scene releases are still going to be `.mkv` so I guess that's not a big deal really... Though I am sure I _do_ have `.mp4` and `.avi` in my collection...

**Comment by mmgoodnow** [comment]
Yeah, it probably is a Jackett bug. Digging into it a little more, [I think this line is the culprit](https://github.com/Jackett/Jackett/blob/38bd2cc2f2d9f45e82d83fdb02a30e63b0357849/src/Jackett.Common/Indexers/DigitalCore.cs#L209).

I'll put up a PR over there in addition to catching the errors over here, but I'd love it if you could test the Jackett change.

**Comment by bjeanes** [comment]
> I'd love it if you could test the Jackett change.

Can do. Ping me on the eventual PR and I'll see what I can do.

**Comment by mmgoodnow** [comment]
v1.3.8 should be good to go!

https://github.com/mmgoodnow/cross-seed/compare/v1.3.6...v1.3.8

**Comment by mmgoodnow** [comment]
Hmm. Digging in further, it seems like this Jackett bug may be a bit larger in scope than I originally thought...

**Comment by bjeanes** [comment]
Hmm that's odd!

Anyway, I just tested this out. I no longer get the JSON error but instead just a vague:

```
error querying Jackett for <file name>
```

That's printed out for every item found in the directory (now 26 suitable torrents).

FWIW, I'm basically running the app like so:

``` yml
services:
  cross-seed:
    # no cross-seed Docker image, so just installing it on boot inside node container
    image: node 
    container_name: cross-seed
    restart: unless-stopped
    volumes:
      - "$MEDIA/Downloads/torrents/finished:/data/finished-torrents"
      - "$MEDIA/Downloads/torrents/cross-seed:/data/cross-seed"
    environment:
      JACKETT_API_KEY: <REDACTED>
    command: sh -c "
      npm i -g cross-seed;
      cross-seed search -d 60 -e -u http://localhost:9117/ -k $$JACKETT_API_KEY -t milkie,aither,digitalcore -i /data/finished-torrents -s /data/cross-seed
      "
```

**Comment by mmgoodnow** [comment]
Hmm. I think I was way off base with the new lines. I've been working on it today and can't repro the "Unexpected end of input" error message. 

Are you sure your jackett config is set up correctly? Maybe you need a base url?

I know the error handling is pretty lacking, I have plans to add some debug logging to the app in the future to hopefully make this easier.

**Comment by bjeanes** [comment]
> Are you sure your jackett config is set up correctly? Maybe you need a base url?

AFAIK. I have tried with and without the `/jackett` base url (as you've used in your README) but the actual API routes do _not_ prefix `/jackett`. With or without appears to make no difference. Without some debug output I think I can only speculate at the underlying cause.

**Comment by mmgoodnow** [comment]
Try v1.3.9, I think your problem is a trailing slash after 9117.

**Comment by bjeanes** [comment]
Yup that did it. Thanks!
