### ISSUE TITLE
Incomplete torrents get cached as a failure and not retried

### ISSUE THREAD

**Issue by ajhorvath20** [mmgoodnow/cross-seed#73]
Hi,

I just noticed `cross-seed` search for a torrent and then added into cache when file was still downloading. Because file went into cache then cross-seed never injected the torrent into qbittorrent.

cross-seed log
![image](https://user-images.githubusercontent.com/65309559/118712201-677e7a00-b818-11eb-8cf5-6e39895a8732.png)

In cache folder
![image](https://user-images.githubusercontent.com/65309559/118712085-428a0700-b818-11eb-85d7-42ddc821855c.png)

Thanks

**Comment by mmgoodnow** [comment]
This is a known limitation of `cross-seed search` and as currently designed, the app just doesn't have access to enough information to prevent that. Currently the only way to get around this is to use Daemon mode.

**Comment by mmgoodnow** [comment]
Hmm, on second thought we should be able to skip saving it to the cache, at the very least.

**Comment by ajhorvath20** [comment]
> Hmm, on second thought we should be able to skip saving it to the cache, at the very least.

Yes that would be great if avoiding saving the file in a cache if its still downloading.

**Comment by mmgoodnow** [comment]
Ah, so taking a look at this again, I'm not sure there's a bug here. I'm assuming this was part of a run of search mode (let me know if it wasn't). If you run it again after the download has finished, does it still not get injected?

**Comment by mmgoodnow** [comment]
Are you using `excludeOlder`/`excludeRecentSearch`?

**Comment by mmgoodnow** [comment]
As of https://github.com/mmgoodnow/cross-seed/releases/tag/v2.3.6, torrents will not be considered "searched" by the `excludeOlder`/`excludeRecentSearch` flags if the download is unfinished.

**Comment by ajhorvath20** [comment]
> Are you using `excludeOlder`/`excludeRecentSearch`?

Hi, no I am only using `command: search`.

**Comment by mmgoodnow** [comment]
If you run search mode again after the download has finished, does it get injected then?

**Comment by ajhorvath20** [comment]
> If you run search mode again after the download has finished, does it get injected then?

I have search mode always running but previously where cross-seed cache the file because it was half downloaded still not injected. But I didn't pull the new image tho.

**Comment by mmgoodnow** [comment]
I'm still not sure I understand what's going on here. 

> Because file went into cache then cross-seed never injected the torrent into qbittorrent.

That's not really how the logic works. The file being cached doesn't have any impact on whether or not the torrent gets injected during the next run.

How often are you running cross-seed? Or are you using the daemon?

**Comment by ajhorvath20** [comment]
> I'm still not sure I understand what's going on here.
> 
> > Because file went into cache then cross-seed never injected the torrent into qbittorrent.
> 
> That's not really how the logic works. The file being cached doesn't have any impact on whether or not the torrent gets injected during the next run.
> 
> How often are you running cross-seed? Or are you using the daemon?

Hi, I'm running `command: search` and `delay: 60` so its running all the time.

**Comment by mmgoodnow** [comment]
Any updates here?

**Comment by ajhorvath20** [comment]
Oops I should update this earlier but I opened so many issues and completely forgot to close this. 

Yes this one is working awesome as you already fixed it few weeks or month ago. 

Thanks again
