### ISSUE TITLE
Migrate to Winston for logging

### ISSUE THREAD

**Issue by Drazzilb08** [mmgoodnow/cross-seed#75]
While doing troubleshooting it would be great for the script to actually create log files in the `/config` dir. 

I've recently only been relying on the log files within docker which does not have time stamps for at least starts and ends of the script running w/in the container. 

Having the creation of a log file would allow for me to view the entire log for each run much easier w/in a text editor

**Comment by mmgoodnow** [comment]
Good idea.

**Comment by mmgoodnow** [comment]
Do you have any input as to how you'd want this to be prioritized on the [roadmap](https://github.com/mmgoodnow/cross-seed/project/1)?

**Comment by Drazzilb08** [comment]
I think it should be pretty high priority as it can help with debugging and support requests. As you know. "It didn't happen unless there are logs."

**Comment by ajhorvath20** [comment]
Yes definitely thats the one. Nice one drazzilb

**Comment by mmgoodnow** [comment]
It has been moved to the top of the list. Hoping to get it done today

**Comment by Drazzilb08** [comment]
Good to hear. With better logs we can help more with debugging. And make this even more bad @ss

**Comment by mmgoodnow** [comment]
This has been added in version 2.4.0 🎉

**Comment by Drazzilb08** [comment]
@mmgoodnow  I'll test this puppy out tomorrow. Are there any env variables to make this work with the container. Haven't checked to see if you've gotten around to update the docs.

**Comment by mmgoodnow** [comment]
> @mmgoodnow  I'll test this puppy out tomorrow. Are there any env variables to make this work with the container. Haven't checked to see if you've gotten around to update the docs. 

Thanks for your help! It should just automatically create a logs folder in your config dir.

**Comment by afraazali** [comment]
Logs are working for me. Appreciate the split up between info, error and verbose. I've been running it in a docker container for the last 5 hours or so on 10 min interval with cron. So far no issues.
