### ISSUE TITLE
0 suitable to search for matches

### ISSUE THREAD

**Issue by adamwinn** [mmgoodnow/cross-seed#8]
```
adamwinn@DiskStation:~/scripts$ cross-seed search -u http://xxxxx:9117 -k xxxxxx -d 10 -t all -i ~/scripts/ -s ~/scripts/matches
Found 1 torrents, 0 suitable to search for matches
Done! Found 0 cross seeds from 0 original torrents
adamwinn@DiskStation:~/scripts$ cross-seed -v
1.3.9
```
The torrent file is `[MTV]Murder in the Car Park - Murder.in.the.Car.Park.S01E01.1080p.HDTV.H264-LiNKLE - 2020 (HDTV - h264 - 1080p).torrent`

Why is it not suitable to search for matches?  A reason why in the output would be nice

**Comment by mmgoodnow** [comment]
Hi! `cross-seed` is designed for long-term seeding, and as such does not try to search for matches for single-episode torrents.

I do have plans to add some better logging so this will be a little more apparent in the future.

**Comment by adamwinn** [comment]
An update of the README.md would probably be best too since that's not stated anywhere

**Comment by mmgoodnow** [comment]
Whoops. It turns out that I actually did write support for single-episode torrents a while back! You can use the `-e` command line flag or `includeEpisodes: true` in the config file.
