### ISSUE TITLE
Prowlarr 

### ISSUE THREAD

**Issue by afraazali** [mmgoodnow/cross-seed#83]
I’m not sure if this is possible quite yet as prowlarr (https://github.com/Prowlarr/Prowlarr/releases/tag/v0.1.0.361) is in its infancy, but it seems to be a replacement for jackett.

**Comment by mmgoodnow** [comment]
I'm going to close this out. I have no immediate plans to add prowlarr integration for the following reasons:
- it would be a significant amount of work - currently I'm using the private Jackett JSON api, not Torznab. If I were ever to support both I would use Torznab. 
- In order for Jackett competitors to succeed they need to continuously support **hundreds** of trackers. Seeing as Prowlarr is very young, I'd like to see it mature into a stable version that supports many trackers and keeps up with maintenance first. 
Feel free to reopen or comment again when you think that Prowlarr has proven that its in it for the long haul.

**Comment by bakerboy448** [comment]
As requested: adding my comments from #104 

would likely need to use the /search and /indexer endpoints; no /all exists nor is it planned for an aggregate endpoint to exist

I see https://github.com/mmgoodnow/cross-seed/issues/83 was closed

so to address some of those comments


>it would be a significant amount of work - currently I'm using the private Jackett JSON api, not Torznab. If I were ever to support both I would use Torznab.

Indeed.  Anything on the prowlarr side that can be done to make this easier?

> In order for Jackett competitors to succeed they need to continuously support hundreds of trackers. Seeing as Prowlarr is very young, I'd like to see it mature into a stable version that supports many trackers and keeps up with maintenance first.
Feel free to reopen or comment again when you think that Prowlarr has proven that its in it for the long haul.

> continuously support hundreds of trackers

Yup, we do.

> stable version

Betas are rolling along and working in PROD without issue by a few thousand.  and the initial alpha group has been using it in Prod since Feb/March

> keeps up with maintenance first.

on top of it

> Prowlarr has proven that its in it for the long haul.

It's the Servarr team that brought you Readarr/Lidarr/Radarr (and the Servarr Wiki), so yes.

**Comment by bakerboy448** [comment]
some search endpoint details
https://github.com/Prowlarr/Prowlarr/issues/427#issuecomment-903293404

**Comment by mmgoodnow** [comment]
@bakerboy448 is there a recommended way to map from jackett string-based tracker ids to prowlarr number-based ids?

**Comment by bakerboy448** [comment]
@Qstick any additional ideas?

can't really compare jackett <-> prowlarr, too many changes 😥 

indexer IDs are going to very for every user and are based on when the user added an indexer.  They're the DB ID entry for the user's configured indexer, but an ID for any specific indexer.

Indexer Names are also input by the user

Your simplest approach would be - similar to the current implementation with jackett - It'd be on the user to input the indexerids they wish to use.
![image](https://user-images.githubusercontent.com/55419169/130527227-05f35855-0344-4431-9773-9272f3199fa1.png)


Some examples responses from the prowlarr/indexer endpoint
https://gist.github.com/bakerboy448/437fad13bfe20d92ae7b67cb66e14d0a
https://gist.github.com/bakerboy448/1f90a5eb9e6848ba867aee473e1e917a

**Comment by bakerboy448** [comment]
I'd also suggest considering searching the exact torrent name; tho an option to replace `.` with ` ` and vice versa may be useful then

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/prowlarr/search#search-feed May help as well

**Comment by danktankk** [comment]
well, here we are at christmas and I am definitely hoping we can snag a little bit of prowlarr love now?

**Comment by danktankk** [comment]
lol got a thumbs down from a cocksucker named jerrk.  im my opinion thats a thumbs up. LMAO

**Comment by danktankk** [comment]
tell you what..  mark my prowlarr comment off topic in a fucking prowlarr post?  fuck you and fuck your script

**Comment by danktankk** [comment]
well, here we are at christmas and I am definitely hoping we can snag a little bit of prowlarr love now?

this is based on your post here:  
https://github.com/mmgoodnow/cross-seed/issues/83#issuecomment-952967573

so its definitely ON TOPIC

**Comment by danktankk** [comment]
hey fuck you :)

**Comment by danktankk** [comment]
danktankk 16 minutes ago
well, here we are at christmas and I am definitely hoping we can snag a little bit of prowlarr love now?

this is based on your post here:
#83 (comment)

so its definitely ON TOPIC

**Comment by danktankk** [comment]
if you dont want to do it, say so you fucking coward.  dont hide.

**Comment by danktankk** [comment]
we waiting until christmas, its christmas....  YOU said christmas, not us.

**Comment by mmgoodnow** [comment]
@bakerboy448 a few questions:

- Is there any way we can get some sort of string form of a tracker's name in the torznab response; either search (ideal), caps or both? It could totally be the user-input name. Right now, from Torznab, it seems like it's entirely invisible which tracker is which. The only thing I have to differentiate them is the id in the torznab url. This is important for the logging:
```
info: Found Movie.1999.1080p.BluRay.DD5.1.x264-GROUP.mkv on tracker1
info: Found Movie.1999.1080p.BluRay.DD5.1.x264-GROUP.mkv on tracker2
info: Found Movie.1999.1080p.BluRay.DD5.1.x264-GROUP.mkv on tracker3
info: Found Movie.1999.1080p.BluRay.DD5.1.x264-GROUP.mkv on tracker4
```
- secondly, how do guids work in Prowlarr? Are they truly globally unique? I'm seeing things like Gazelle-123456 which seem like they could possibly be unique only within trackers.

**Comment by bakerboy448** [comment]
Indexer name you can also get from the indexerapi endpoint.  The IDs are specific for that given instance of an indexer so that won't change 


GUID I believe is from the indexer  itself - not calculated by Prowlarr

**Comment by mmgoodnow** [comment]
Does that mean the ids are not globally unique then? I'll forge ahead but that could definitely cause some subtle bugs

**Comment by bakerboy448** [comment]
Looking at both Jackett and prowlarr code - the GUID is from the tracker not from the app itself.

**Comment by mmgoodnow** [comment]
In Jackett they just use the comments url as the guid. It ensures uniqueness across trackers (globally) because it contains the tracker's domain name. However this does not seem to be the case with Prowlarr - two trackers both using Gazelle could easily cause GUID collisions.

**Comment by bakerboy448** [comment]
Gazelle GUID is formed based on the release ID from the indexer

https://github.com/Prowlarr/Prowlarr/blob/a5e13ca776b629a432a389981235e77f350a915d/src/NzbDrone.Core/Indexers/Definitions/Gazelle/GazelleParser.cs#L101

**Comment by mmgoodnow** [comment]
In that case it's definitely a bug, albeit a minor one. Pulling the torrentId straight from the tracker means that, while the guid is tracker-unique, it's not _**globally**_ unique (which is what guids are supposed to be). 

Jackett's guids don't have this problem because the comments urls contain _both_ the torrentId and the tracker's domain name.

This will cause problems in cross-seed because we use guids as dictionary keys in the cache, so in the event of a collision, there's a chance of false positives.

I can file an issue for that in Prowlarr if you'd like.

**Comment by bakerboy448** [comment]
Should be an easy fix, go ahead and toss one up so we don't forget

**Comment by bakerboy448** [comment]
Fixed in Prowlarr nightly

**Comment by mmgoodnow** [comment]
Actually, @bakerboy448/@Qstick, what would you think about making the title tag at xpath `/rss/channel/title` in the torznab t=search output say the tracker name instead of just "Prowlarr"? It could say something like `TehConnection (Prowlarr)` if you want to preserve prowlarr's watermark on the feed.

Jackett does it that way, which I realize is not a great reason to do something, but it also seems like a reasonable thing to do, and it would not require special casing across jackett, prowlarr, or other torznab implementations.

**Comment by Qstick** [comment]
> Actually, @bakerboy448 / @Qstick, what would you think about making the title tag at xpath `/rss/channel/title` in the torznab t=search output say the tracker name instead of just "Prowlarr"? It could say something like `TehConnection (Prowlarr)` if you want to preserve prowlarr's watermark on the feed.
> 
> Jackett does it that way, which I realize is not a great reason to do something, but it also seems like a reasonable thing to do, and it would not require special casing across jackett, prowlarr, or other torznab implementations.

It’s on the list, but needs some refactoring on our side to do

**Comment by mmgoodnow** [comment]
got an issue link I can follow along to? Alternatively feel free to just ping me when it's done.

**Comment by mmgoodnow** [comment]
> I'd also suggest considering searching the exact torrent name; tho an option to replace . with and vice versa may be useful then

Just tried it; seems to be too restrictive. I also tried doing this with Jackett way back in v1 and most tracker search functionality just doesn't do well with exact-string searching. Gonna go ahead and do the same reformatting we were using for Jackett, that looks like it works well for Prowlarr as well

**Comment by mmgoodnow** [comment]
Time for user testing! [Head on over to the PR here](https://github.com/mmgoodnow/cross-seed/pull/179).
