### ISSUE TITLE
Configurable fuzzy matching

### ISSUE THREAD

**Issue by newadventure079** [mmgoodnow/cross-seed#84]
I noticed pull request https://github.com/mmgoodnow/cross-seed/pull/32 which upped the boundary for matching a torrent.  I think it should be taken a step further and allow that matching amount to be a user input (the default value would be left to how it is now and only changed if the user wanted to use the new input option).  This would allow for values, such as `.1 * length` or even `.2 * length` for torrents that include samples, nfos, subtitles and other stuff.  This would be useful for people who dont mind having a few extra torrent matches that aren't 100% and also want to seed ones they have that are 80% completed and will download the missing 20% and then begin seeding

Relevant code:
```
const lowerBound = length - 0.02 * length;
const upperBound = length + 0.02 * length;
```

**Comment by mmgoodnow** [comment]
I like that idea. I'll add it to the backlog, but pull requests are always welcome!

**Comment by ClandestineClout** [comment]
Definitely a good idea +1

**Comment by mmgoodnow** [comment]
I've merged @jasonhazel's PR. No guarantees from me on it working well.
