### ISSUE TITLE
cross-seed is not downloading all available releases

### ISSUE THREAD

**Issue by rj-d2** [mmgoodnow/cross-seed#92]
Hi,

first of all i love cross-seed, awesome tool.

im seeding something like this:
`The.Movie.2021.1080p.AMZN.WEB-DL.DDP5.1.H.264-GROUP
`
cross-seed searched and found 6 torrents

when i search jackett manually with:
`The Movie 2021 1080p AMZN WEB-DL GROUP
`
i find 10 torrents wich all can be imported by autotorrent

is this expected?
can cross-seed strip the search term on jackett down a bit to get better results,
or would this lead to too many false positives?

**Comment by mmgoodnow** [comment]
It does strip the search term on jackett, you can see with the verbose option turned on. 

Those other torrents are getting ruled out for some reason.

**Comment by rj-d2** [comment]
Hi,

i was digging around in the verbose log and found something,

cross-seed searching for: "Series Year S01E01"
finds only 1 torrent

manually searching jackett for: "Series S01E01" finds 5 matching torrents.

**Comment by mmgoodnow** [comment]
`Series Year` is often a different show from `Series`. (for example, iCarly vs iCarly 2021). They put the year on the later one. Unfortunately there's not much we can do here atm. The `decide` phase should prevent false positives but cross-seed is just parsing the title as best it can from the torrent name, not doing any TVDB lookups or anything like that. So it makes a best guess. 

There's not really anything actionable here, so I'm going to close it out. In the future we'll be doing Torznab queries which may  help but discovery is heavily dependent on the search engines built into each tracker and will always vary across trackers.
