### ISSUE TITLE
its size does not match - Even though the size does match

### ISSUE THREAD

**Issue by pummra** [mmgoodnow/cross-seed#97]
Trying to match between trackers and getting this error back when I check on verbose. I have compared the two torrents by hand and they are the same size, no additional files etc. 

Any reason cross-seed might think they are different sizes?

**Comment by afraazali** [comment]
Are there any extra files, like nfo's or samples? I get this warning lot for some of my trackers that add sample files.

**Comment by pummra** [comment]
Ah right, there was an nfo I didn't see in the first instance. Will close this.
